// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BEVFusionConfig.proto

#ifndef PROTOBUF_INCLUDED_BEVFusionConfig_2eproto
#define PROTOBUF_INCLUDED_BEVFusionConfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "CameraConfig.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_BEVFusionConfig_2eproto 

namespace protobuf_BEVFusionConfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_BEVFusionConfig_2eproto
namespace bevfusion {
class BEVFusionConfig;
class BEVFusionConfigDefaultTypeInternal;
extern BEVFusionConfigDefaultTypeInternal _BEVFusionConfig_default_instance_;
class GeometryConfig;
class GeometryConfigDefaultTypeInternal;
extern GeometryConfigDefaultTypeInternal _GeometryConfig_default_instance_;
class LidarConfig;
class LidarConfigDefaultTypeInternal;
extern LidarConfigDefaultTypeInternal _LidarConfig_default_instance_;
class ModelPaths;
class ModelPathsDefaultTypeInternal;
extern ModelPathsDefaultTypeInternal _ModelPaths_default_instance_;
class PostprocessorConfig;
class PostprocessorConfigDefaultTypeInternal;
extern PostprocessorConfigDefaultTypeInternal _PostprocessorConfig_default_instance_;
}  // namespace bevfusion
namespace google {
namespace protobuf {
template<> ::bevfusion::BEVFusionConfig* Arena::CreateMaybeMessage<::bevfusion::BEVFusionConfig>(Arena*);
template<> ::bevfusion::GeometryConfig* Arena::CreateMaybeMessage<::bevfusion::GeometryConfig>(Arena*);
template<> ::bevfusion::LidarConfig* Arena::CreateMaybeMessage<::bevfusion::LidarConfig>(Arena*);
template<> ::bevfusion::ModelPaths* Arena::CreateMaybeMessage<::bevfusion::ModelPaths>(Arena*);
template<> ::bevfusion::PostprocessorConfig* Arena::CreateMaybeMessage<::bevfusion::PostprocessorConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bevfusion {

// ===================================================================

class BEVFusionConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bevfusion.BEVFusionConfig) */ {
 public:
  BEVFusionConfig();
  virtual ~BEVFusionConfig();

  BEVFusionConfig(const BEVFusionConfig& from);

  inline BEVFusionConfig& operator=(const BEVFusionConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BEVFusionConfig(BEVFusionConfig&& from) noexcept
    : BEVFusionConfig() {
    *this = ::std::move(from);
  }

  inline BEVFusionConfig& operator=(BEVFusionConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BEVFusionConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BEVFusionConfig* internal_default_instance() {
    return reinterpret_cast<const BEVFusionConfig*>(
               &_BEVFusionConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BEVFusionConfig* other);
  friend void swap(BEVFusionConfig& a, BEVFusionConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BEVFusionConfig* New() const final {
    return CreateMaybeMessage<BEVFusionConfig>(NULL);
  }

  BEVFusionConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BEVFusionConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BEVFusionConfig& from);
  void MergeFrom(const BEVFusionConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BEVFusionConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .bevfusion.CameraConfig cameras = 4;
  int cameras_size() const;
  void clear_cameras();
  static const int kCamerasFieldNumber = 4;
  ::bevfusion::CameraConfig* mutable_cameras(int index);
  ::google::protobuf::RepeatedPtrField< ::bevfusion::CameraConfig >*
      mutable_cameras();
  const ::bevfusion::CameraConfig& cameras(int index) const;
  ::bevfusion::CameraConfig* add_cameras();
  const ::google::protobuf::RepeatedPtrField< ::bevfusion::CameraConfig >&
      cameras() const;

  // string model_name = 5;
  void clear_model_name();
  static const int kModelNameFieldNumber = 5;
  const ::std::string& model_name() const;
  void set_model_name(const ::std::string& value);
  #if LANG_CXX11
  void set_model_name(::std::string&& value);
  #endif
  void set_model_name(const char* value);
  void set_model_name(const char* value, size_t size);
  ::std::string* mutable_model_name();
  ::std::string* release_model_name();
  void set_allocated_model_name(::std::string* model_name);

  // string precision = 6;
  void clear_precision();
  static const int kPrecisionFieldNumber = 6;
  const ::std::string& precision() const;
  void set_precision(const ::std::string& value);
  #if LANG_CXX11
  void set_precision(::std::string&& value);
  #endif
  void set_precision(const char* value);
  void set_precision(const char* value, size_t size);
  ::std::string* mutable_precision();
  ::std::string* release_precision();
  void set_allocated_precision(::std::string* precision);

  // .bevfusion.LidarConfig lidar_config = 7;
  bool has_lidar_config() const;
  void clear_lidar_config();
  static const int kLidarConfigFieldNumber = 7;
  private:
  const ::bevfusion::LidarConfig& _internal_lidar_config() const;
  public:
  const ::bevfusion::LidarConfig& lidar_config() const;
  ::bevfusion::LidarConfig* release_lidar_config();
  ::bevfusion::LidarConfig* mutable_lidar_config();
  void set_allocated_lidar_config(::bevfusion::LidarConfig* lidar_config);

  // .bevfusion.GeometryConfig geometry_config = 8;
  bool has_geometry_config() const;
  void clear_geometry_config();
  static const int kGeometryConfigFieldNumber = 8;
  private:
  const ::bevfusion::GeometryConfig& _internal_geometry_config() const;
  public:
  const ::bevfusion::GeometryConfig& geometry_config() const;
  ::bevfusion::GeometryConfig* release_geometry_config();
  ::bevfusion::GeometryConfig* mutable_geometry_config();
  void set_allocated_geometry_config(::bevfusion::GeometryConfig* geometry_config);

  // .bevfusion.PostprocessorConfig postprocessor_config = 9;
  bool has_postprocessor_config() const;
  void clear_postprocessor_config();
  static const int kPostprocessorConfigFieldNumber = 9;
  private:
  const ::bevfusion::PostprocessorConfig& _internal_postprocessor_config() const;
  public:
  const ::bevfusion::PostprocessorConfig& postprocessor_config() const;
  ::bevfusion::PostprocessorConfig* release_postprocessor_config();
  ::bevfusion::PostprocessorConfig* mutable_postprocessor_config();
  void set_allocated_postprocessor_config(::bevfusion::PostprocessorConfig* postprocessor_config);

  // .bevfusion.ModelPaths model_paths = 10;
  bool has_model_paths() const;
  void clear_model_paths();
  static const int kModelPathsFieldNumber = 10;
  private:
  const ::bevfusion::ModelPaths& _internal_model_paths() const;
  public:
  const ::bevfusion::ModelPaths& model_paths() const;
  ::bevfusion::ModelPaths* release_model_paths();
  ::bevfusion::ModelPaths* mutable_model_paths();
  void set_allocated_model_paths(::bevfusion::ModelPaths* model_paths);

  // float confidence_threshold = 1;
  void clear_confidence_threshold();
  static const int kConfidenceThresholdFieldNumber = 1;
  float confidence_threshold() const;
  void set_confidence_threshold(float value);

  // bool enable_timer = 2;
  void clear_enable_timer();
  static const int kEnableTimerFieldNumber = 2;
  bool enable_timer() const;
  void set_enable_timer(bool value);

  // uint32 num_camera = 3;
  void clear_num_camera();
  static const int kNumCameraFieldNumber = 3;
  ::google::protobuf::uint32 num_camera() const;
  void set_num_camera(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:bevfusion.BEVFusionConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::bevfusion::CameraConfig > cameras_;
  ::google::protobuf::internal::ArenaStringPtr model_name_;
  ::google::protobuf::internal::ArenaStringPtr precision_;
  ::bevfusion::LidarConfig* lidar_config_;
  ::bevfusion::GeometryConfig* geometry_config_;
  ::bevfusion::PostprocessorConfig* postprocessor_config_;
  ::bevfusion::ModelPaths* model_paths_;
  float confidence_threshold_;
  bool enable_timer_;
  ::google::protobuf::uint32 num_camera_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BEVFusionConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LidarConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bevfusion.LidarConfig) */ {
 public:
  LidarConfig();
  virtual ~LidarConfig();

  LidarConfig(const LidarConfig& from);

  inline LidarConfig& operator=(const LidarConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LidarConfig(LidarConfig&& from) noexcept
    : LidarConfig() {
    *this = ::std::move(from);
  }

  inline LidarConfig& operator=(LidarConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LidarConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LidarConfig* internal_default_instance() {
    return reinterpret_cast<const LidarConfig*>(
               &_LidarConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(LidarConfig* other);
  friend void swap(LidarConfig& a, LidarConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LidarConfig* New() const final {
    return CreateMaybeMessage<LidarConfig>(NULL);
  }

  LidarConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LidarConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LidarConfig& from);
  void MergeFrom(const LidarConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LidarConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float min_range = 1;
  int min_range_size() const;
  void clear_min_range();
  static const int kMinRangeFieldNumber = 1;
  float min_range(int index) const;
  void set_min_range(int index, float value);
  void add_min_range(float value);
  const ::google::protobuf::RepeatedField< float >&
      min_range() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_min_range();

  // repeated float max_range = 2;
  int max_range_size() const;
  void clear_max_range();
  static const int kMaxRangeFieldNumber = 2;
  float max_range(int index) const;
  void set_max_range(int index, float value);
  void add_max_range(float value);
  const ::google::protobuf::RepeatedField< float >&
      max_range() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_max_range();

  // repeated float voxel_size = 3;
  int voxel_size_size() const;
  void clear_voxel_size();
  static const int kVoxelSizeFieldNumber = 3;
  float voxel_size(int index) const;
  void set_voxel_size(int index, float value);
  void add_voxel_size(float value);
  const ::google::protobuf::RepeatedField< float >&
      voxel_size() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_voxel_size();

  // repeated float grid_size = 4;
  int grid_size_size() const;
  void clear_grid_size();
  static const int kGridSizeFieldNumber = 4;
  float grid_size(int index) const;
  void set_grid_size(int index, float value);
  void add_grid_size(float value);
  const ::google::protobuf::RepeatedField< float >&
      grid_size() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_grid_size();

  // string lidar_model_path = 9;
  void clear_lidar_model_path();
  static const int kLidarModelPathFieldNumber = 9;
  const ::std::string& lidar_model_path() const;
  void set_lidar_model_path(const ::std::string& value);
  #if LANG_CXX11
  void set_lidar_model_path(::std::string&& value);
  #endif
  void set_lidar_model_path(const char* value);
  void set_lidar_model_path(const char* value, size_t size);
  ::std::string* mutable_lidar_model_path();
  ::std::string* release_lidar_model_path();
  void set_allocated_lidar_model_path(::std::string* lidar_model_path);

  // string coordinate_order = 10;
  void clear_coordinate_order();
  static const int kCoordinateOrderFieldNumber = 10;
  const ::std::string& coordinate_order() const;
  void set_coordinate_order(const ::std::string& value);
  #if LANG_CXX11
  void set_coordinate_order(::std::string&& value);
  #endif
  void set_coordinate_order(const char* value);
  void set_coordinate_order(const char* value, size_t size);
  ::std::string* mutable_coordinate_order();
  ::std::string* release_coordinate_order();
  void set_allocated_coordinate_order(::std::string* coordinate_order);

  // uint32 max_points_per_voxel = 5;
  void clear_max_points_per_voxel();
  static const int kMaxPointsPerVoxelFieldNumber = 5;
  ::google::protobuf::uint32 max_points_per_voxel() const;
  void set_max_points_per_voxel(::google::protobuf::uint32 value);

  // uint32 max_points = 6;
  void clear_max_points();
  static const int kMaxPointsFieldNumber = 6;
  ::google::protobuf::uint32 max_points() const;
  void set_max_points(::google::protobuf::uint32 value);

  // uint32 max_voxels = 7;
  void clear_max_voxels();
  static const int kMaxVoxelsFieldNumber = 7;
  ::google::protobuf::uint32 max_voxels() const;
  void set_max_voxels(::google::protobuf::uint32 value);

  // uint32 num_feature = 8;
  void clear_num_feature();
  static const int kNumFeatureFieldNumber = 8;
  ::google::protobuf::uint32 num_feature() const;
  void set_num_feature(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:bevfusion.LidarConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > min_range_;
  mutable int _min_range_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > max_range_;
  mutable int _max_range_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > voxel_size_;
  mutable int _voxel_size_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > grid_size_;
  mutable int _grid_size_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr lidar_model_path_;
  ::google::protobuf::internal::ArenaStringPtr coordinate_order_;
  ::google::protobuf::uint32 max_points_per_voxel_;
  ::google::protobuf::uint32 max_points_;
  ::google::protobuf::uint32 max_voxels_;
  ::google::protobuf::uint32 num_feature_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BEVFusionConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GeometryConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bevfusion.GeometryConfig) */ {
 public:
  GeometryConfig();
  virtual ~GeometryConfig();

  GeometryConfig(const GeometryConfig& from);

  inline GeometryConfig& operator=(const GeometryConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GeometryConfig(GeometryConfig&& from) noexcept
    : GeometryConfig() {
    *this = ::std::move(from);
  }

  inline GeometryConfig& operator=(GeometryConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GeometryConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GeometryConfig* internal_default_instance() {
    return reinterpret_cast<const GeometryConfig*>(
               &_GeometryConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GeometryConfig* other);
  friend void swap(GeometryConfig& a, GeometryConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GeometryConfig* New() const final {
    return CreateMaybeMessage<GeometryConfig>(NULL);
  }

  GeometryConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GeometryConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GeometryConfig& from);
  void MergeFrom(const GeometryConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeometryConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float xbound = 1;
  int xbound_size() const;
  void clear_xbound();
  static const int kXboundFieldNumber = 1;
  float xbound(int index) const;
  void set_xbound(int index, float value);
  void add_xbound(float value);
  const ::google::protobuf::RepeatedField< float >&
      xbound() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_xbound();

  // repeated float ybound = 2;
  int ybound_size() const;
  void clear_ybound();
  static const int kYboundFieldNumber = 2;
  float ybound(int index) const;
  void set_ybound(int index, float value);
  void add_ybound(float value);
  const ::google::protobuf::RepeatedField< float >&
      ybound() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_ybound();

  // repeated float zbound = 3;
  int zbound_size() const;
  void clear_zbound();
  static const int kZboundFieldNumber = 3;
  float zbound(int index) const;
  void set_zbound(int index, float value);
  void add_zbound(float value);
  const ::google::protobuf::RepeatedField< float >&
      zbound() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_zbound();

  // repeated float dbound = 4;
  int dbound_size() const;
  void clear_dbound();
  static const int kDboundFieldNumber = 4;
  float dbound(int index) const;
  void set_dbound(int index, float value);
  void add_dbound(float value);
  const ::google::protobuf::RepeatedField< float >&
      dbound() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_dbound();

  // repeated uint32 geometry_dim = 10;
  int geometry_dim_size() const;
  void clear_geometry_dim();
  static const int kGeometryDimFieldNumber = 10;
  ::google::protobuf::uint32 geometry_dim(int index) const;
  void set_geometry_dim(int index, ::google::protobuf::uint32 value);
  void add_geometry_dim(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      geometry_dim() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_geometry_dim();

  // uint32 image_width = 5;
  void clear_image_width();
  static const int kImageWidthFieldNumber = 5;
  ::google::protobuf::uint32 image_width() const;
  void set_image_width(::google::protobuf::uint32 value);

  // uint32 image_height = 6;
  void clear_image_height();
  static const int kImageHeightFieldNumber = 6;
  ::google::protobuf::uint32 image_height() const;
  void set_image_height(::google::protobuf::uint32 value);

  // uint32 feat_width = 7;
  void clear_feat_width();
  static const int kFeatWidthFieldNumber = 7;
  ::google::protobuf::uint32 feat_width() const;
  void set_feat_width(::google::protobuf::uint32 value);

  // uint32 feat_height = 8;
  void clear_feat_height();
  static const int kFeatHeightFieldNumber = 8;
  ::google::protobuf::uint32 feat_height() const;
  void set_feat_height(::google::protobuf::uint32 value);

  // uint32 num_camera = 9;
  void clear_num_camera();
  static const int kNumCameraFieldNumber = 9;
  ::google::protobuf::uint32 num_camera() const;
  void set_num_camera(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:bevfusion.GeometryConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > xbound_;
  mutable int _xbound_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > ybound_;
  mutable int _ybound_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > zbound_;
  mutable int _zbound_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > dbound_;
  mutable int _dbound_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > geometry_dim_;
  mutable int _geometry_dim_cached_byte_size_;
  ::google::protobuf::uint32 image_width_;
  ::google::protobuf::uint32 image_height_;
  ::google::protobuf::uint32 feat_width_;
  ::google::protobuf::uint32 feat_height_;
  ::google::protobuf::uint32 num_camera_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BEVFusionConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PostprocessorConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bevfusion.PostprocessorConfig) */ {
 public:
  PostprocessorConfig();
  virtual ~PostprocessorConfig();

  PostprocessorConfig(const PostprocessorConfig& from);

  inline PostprocessorConfig& operator=(const PostprocessorConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PostprocessorConfig(PostprocessorConfig&& from) noexcept
    : PostprocessorConfig() {
    *this = ::std::move(from);
  }

  inline PostprocessorConfig& operator=(PostprocessorConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PostprocessorConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PostprocessorConfig* internal_default_instance() {
    return reinterpret_cast<const PostprocessorConfig*>(
               &_PostprocessorConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(PostprocessorConfig* other);
  friend void swap(PostprocessorConfig& a, PostprocessorConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PostprocessorConfig* New() const final {
    return CreateMaybeMessage<PostprocessorConfig>(NULL);
  }

  PostprocessorConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PostprocessorConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PostprocessorConfig& from);
  void MergeFrom(const PostprocessorConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PostprocessorConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float pc_range = 2;
  int pc_range_size() const;
  void clear_pc_range();
  static const int kPcRangeFieldNumber = 2;
  float pc_range(int index) const;
  void set_pc_range(int index, float value);
  void add_pc_range(float value);
  const ::google::protobuf::RepeatedField< float >&
      pc_range() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_pc_range();

  // repeated float post_center_range_start = 3;
  int post_center_range_start_size() const;
  void clear_post_center_range_start();
  static const int kPostCenterRangeStartFieldNumber = 3;
  float post_center_range_start(int index) const;
  void set_post_center_range_start(int index, float value);
  void add_post_center_range_start(float value);
  const ::google::protobuf::RepeatedField< float >&
      post_center_range_start() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_post_center_range_start();

  // repeated float post_center_range_end = 4;
  int post_center_range_end_size() const;
  void clear_post_center_range_end();
  static const int kPostCenterRangeEndFieldNumber = 4;
  float post_center_range_end(int index) const;
  void set_post_center_range_end(int index, float value);
  void add_post_center_range_end(float value);
  const ::google::protobuf::RepeatedField< float >&
      post_center_range_end() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_post_center_range_end();

  // repeated float voxel_size = 5;
  int voxel_size_size() const;
  void clear_voxel_size();
  static const int kVoxelSizeFieldNumber = 5;
  float voxel_size(int index) const;
  void set_voxel_size(int index, float value);
  void add_voxel_size(float value);
  const ::google::protobuf::RepeatedField< float >&
      voxel_size() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_voxel_size();

  // uint32 out_size_factor = 1;
  void clear_out_size_factor();
  static const int kOutSizeFactorFieldNumber = 1;
  ::google::protobuf::uint32 out_size_factor() const;
  void set_out_size_factor(::google::protobuf::uint32 value);

  // bool sorted_bboxes = 6;
  void clear_sorted_bboxes();
  static const int kSortedBboxesFieldNumber = 6;
  bool sorted_bboxes() const;
  void set_sorted_bboxes(bool value);

  // @@protoc_insertion_point(class_scope:bevfusion.PostprocessorConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > pc_range_;
  mutable int _pc_range_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > post_center_range_start_;
  mutable int _post_center_range_start_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > post_center_range_end_;
  mutable int _post_center_range_end_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > voxel_size_;
  mutable int _voxel_size_cached_byte_size_;
  ::google::protobuf::uint32 out_size_factor_;
  bool sorted_bboxes_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BEVFusionConfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModelPaths : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bevfusion.ModelPaths) */ {
 public:
  ModelPaths();
  virtual ~ModelPaths();

  ModelPaths(const ModelPaths& from);

  inline ModelPaths& operator=(const ModelPaths& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ModelPaths(ModelPaths&& from) noexcept
    : ModelPaths() {
    *this = ::std::move(from);
  }

  inline ModelPaths& operator=(ModelPaths&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ModelPaths& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelPaths* internal_default_instance() {
    return reinterpret_cast<const ModelPaths*>(
               &_ModelPaths_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ModelPaths* other);
  friend void swap(ModelPaths& a, ModelPaths& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModelPaths* New() const final {
    return CreateMaybeMessage<ModelPaths>(NULL);
  }

  ModelPaths* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ModelPaths>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ModelPaths& from);
  void MergeFrom(const ModelPaths& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelPaths* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string camera_backbone_path = 1;
  void clear_camera_backbone_path();
  static const int kCameraBackbonePathFieldNumber = 1;
  const ::std::string& camera_backbone_path() const;
  void set_camera_backbone_path(const ::std::string& value);
  #if LANG_CXX11
  void set_camera_backbone_path(::std::string&& value);
  #endif
  void set_camera_backbone_path(const char* value);
  void set_camera_backbone_path(const char* value, size_t size);
  ::std::string* mutable_camera_backbone_path();
  ::std::string* release_camera_backbone_path();
  void set_allocated_camera_backbone_path(::std::string* camera_backbone_path);

  // string lidar_backbone_path = 2;
  void clear_lidar_backbone_path();
  static const int kLidarBackbonePathFieldNumber = 2;
  const ::std::string& lidar_backbone_path() const;
  void set_lidar_backbone_path(const ::std::string& value);
  #if LANG_CXX11
  void set_lidar_backbone_path(::std::string&& value);
  #endif
  void set_lidar_backbone_path(const char* value);
  void set_lidar_backbone_path(const char* value, size_t size);
  ::std::string* mutable_lidar_backbone_path();
  ::std::string* release_lidar_backbone_path();
  void set_allocated_lidar_backbone_path(::std::string* lidar_backbone_path);

  // string fuser_path = 3;
  void clear_fuser_path();
  static const int kFuserPathFieldNumber = 3;
  const ::std::string& fuser_path() const;
  void set_fuser_path(const ::std::string& value);
  #if LANG_CXX11
  void set_fuser_path(::std::string&& value);
  #endif
  void set_fuser_path(const char* value);
  void set_fuser_path(const char* value, size_t size);
  ::std::string* mutable_fuser_path();
  ::std::string* release_fuser_path();
  void set_allocated_fuser_path(::std::string* fuser_path);

  // string head_bbox_path = 4;
  void clear_head_bbox_path();
  static const int kHeadBboxPathFieldNumber = 4;
  const ::std::string& head_bbox_path() const;
  void set_head_bbox_path(const ::std::string& value);
  #if LANG_CXX11
  void set_head_bbox_path(::std::string&& value);
  #endif
  void set_head_bbox_path(const char* value);
  void set_head_bbox_path(const char* value, size_t size);
  ::std::string* mutable_head_bbox_path();
  ::std::string* release_head_bbox_path();
  void set_allocated_head_bbox_path(::std::string* head_bbox_path);

  // string camera_vtransform_path = 5;
  void clear_camera_vtransform_path();
  static const int kCameraVtransformPathFieldNumber = 5;
  const ::std::string& camera_vtransform_path() const;
  void set_camera_vtransform_path(const ::std::string& value);
  #if LANG_CXX11
  void set_camera_vtransform_path(::std::string&& value);
  #endif
  void set_camera_vtransform_path(const char* value);
  void set_camera_vtransform_path(const char* value, size_t size);
  ::std::string* mutable_camera_vtransform_path();
  ::std::string* release_camera_vtransform_path();
  void set_allocated_camera_vtransform_path(::std::string* camera_vtransform_path);

  // @@protoc_insertion_point(class_scope:bevfusion.ModelPaths)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr camera_backbone_path_;
  ::google::protobuf::internal::ArenaStringPtr lidar_backbone_path_;
  ::google::protobuf::internal::ArenaStringPtr fuser_path_;
  ::google::protobuf::internal::ArenaStringPtr head_bbox_path_;
  ::google::protobuf::internal::ArenaStringPtr camera_vtransform_path_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_BEVFusionConfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BEVFusionConfig

// float confidence_threshold = 1;
inline void BEVFusionConfig::clear_confidence_threshold() {
  confidence_threshold_ = 0;
}
inline float BEVFusionConfig::confidence_threshold() const {
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.confidence_threshold)
  return confidence_threshold_;
}
inline void BEVFusionConfig::set_confidence_threshold(float value) {
  
  confidence_threshold_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.BEVFusionConfig.confidence_threshold)
}

// bool enable_timer = 2;
inline void BEVFusionConfig::clear_enable_timer() {
  enable_timer_ = false;
}
inline bool BEVFusionConfig::enable_timer() const {
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.enable_timer)
  return enable_timer_;
}
inline void BEVFusionConfig::set_enable_timer(bool value) {
  
  enable_timer_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.BEVFusionConfig.enable_timer)
}

// uint32 num_camera = 3;
inline void BEVFusionConfig::clear_num_camera() {
  num_camera_ = 0u;
}
inline ::google::protobuf::uint32 BEVFusionConfig::num_camera() const {
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.num_camera)
  return num_camera_;
}
inline void BEVFusionConfig::set_num_camera(::google::protobuf::uint32 value) {
  
  num_camera_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.BEVFusionConfig.num_camera)
}

// repeated .bevfusion.CameraConfig cameras = 4;
inline int BEVFusionConfig::cameras_size() const {
  return cameras_.size();
}
inline ::bevfusion::CameraConfig* BEVFusionConfig::mutable_cameras(int index) {
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.cameras)
  return cameras_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::bevfusion::CameraConfig >*
BEVFusionConfig::mutable_cameras() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.BEVFusionConfig.cameras)
  return &cameras_;
}
inline const ::bevfusion::CameraConfig& BEVFusionConfig::cameras(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.cameras)
  return cameras_.Get(index);
}
inline ::bevfusion::CameraConfig* BEVFusionConfig::add_cameras() {
  // @@protoc_insertion_point(field_add:bevfusion.BEVFusionConfig.cameras)
  return cameras_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::bevfusion::CameraConfig >&
BEVFusionConfig::cameras() const {
  // @@protoc_insertion_point(field_list:bevfusion.BEVFusionConfig.cameras)
  return cameras_;
}

// string model_name = 5;
inline void BEVFusionConfig::clear_model_name() {
  model_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BEVFusionConfig::model_name() const {
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.model_name)
  return model_name_.GetNoArena();
}
inline void BEVFusionConfig::set_model_name(const ::std::string& value) {
  
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.BEVFusionConfig.model_name)
}
#if LANG_CXX11
inline void BEVFusionConfig::set_model_name(::std::string&& value) {
  
  model_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.BEVFusionConfig.model_name)
}
#endif
inline void BEVFusionConfig::set_model_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.BEVFusionConfig.model_name)
}
inline void BEVFusionConfig::set_model_name(const char* value, size_t size) {
  
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.BEVFusionConfig.model_name)
}
inline ::std::string* BEVFusionConfig::mutable_model_name() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.model_name)
  return model_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BEVFusionConfig::release_model_name() {
  // @@protoc_insertion_point(field_release:bevfusion.BEVFusionConfig.model_name)
  
  return model_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BEVFusionConfig::set_allocated_model_name(::std::string* model_name) {
  if (model_name != NULL) {
    
  } else {
    
  }
  model_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_name);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.BEVFusionConfig.model_name)
}

// string precision = 6;
inline void BEVFusionConfig::clear_precision() {
  precision_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BEVFusionConfig::precision() const {
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.precision)
  return precision_.GetNoArena();
}
inline void BEVFusionConfig::set_precision(const ::std::string& value) {
  
  precision_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.BEVFusionConfig.precision)
}
#if LANG_CXX11
inline void BEVFusionConfig::set_precision(::std::string&& value) {
  
  precision_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.BEVFusionConfig.precision)
}
#endif
inline void BEVFusionConfig::set_precision(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  precision_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.BEVFusionConfig.precision)
}
inline void BEVFusionConfig::set_precision(const char* value, size_t size) {
  
  precision_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.BEVFusionConfig.precision)
}
inline ::std::string* BEVFusionConfig::mutable_precision() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.precision)
  return precision_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BEVFusionConfig::release_precision() {
  // @@protoc_insertion_point(field_release:bevfusion.BEVFusionConfig.precision)
  
  return precision_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BEVFusionConfig::set_allocated_precision(::std::string* precision) {
  if (precision != NULL) {
    
  } else {
    
  }
  precision_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), precision);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.BEVFusionConfig.precision)
}

// .bevfusion.LidarConfig lidar_config = 7;
inline bool BEVFusionConfig::has_lidar_config() const {
  return this != internal_default_instance() && lidar_config_ != NULL;
}
inline void BEVFusionConfig::clear_lidar_config() {
  if (GetArenaNoVirtual() == NULL && lidar_config_ != NULL) {
    delete lidar_config_;
  }
  lidar_config_ = NULL;
}
inline const ::bevfusion::LidarConfig& BEVFusionConfig::_internal_lidar_config() const {
  return *lidar_config_;
}
inline const ::bevfusion::LidarConfig& BEVFusionConfig::lidar_config() const {
  const ::bevfusion::LidarConfig* p = lidar_config_;
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.lidar_config)
  return p != NULL ? *p : *reinterpret_cast<const ::bevfusion::LidarConfig*>(
      &::bevfusion::_LidarConfig_default_instance_);
}
inline ::bevfusion::LidarConfig* BEVFusionConfig::release_lidar_config() {
  // @@protoc_insertion_point(field_release:bevfusion.BEVFusionConfig.lidar_config)
  
  ::bevfusion::LidarConfig* temp = lidar_config_;
  lidar_config_ = NULL;
  return temp;
}
inline ::bevfusion::LidarConfig* BEVFusionConfig::mutable_lidar_config() {
  
  if (lidar_config_ == NULL) {
    auto* p = CreateMaybeMessage<::bevfusion::LidarConfig>(GetArenaNoVirtual());
    lidar_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.lidar_config)
  return lidar_config_;
}
inline void BEVFusionConfig::set_allocated_lidar_config(::bevfusion::LidarConfig* lidar_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete lidar_config_;
  }
  if (lidar_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      lidar_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, lidar_config, submessage_arena);
    }
    
  } else {
    
  }
  lidar_config_ = lidar_config;
  // @@protoc_insertion_point(field_set_allocated:bevfusion.BEVFusionConfig.lidar_config)
}

// .bevfusion.GeometryConfig geometry_config = 8;
inline bool BEVFusionConfig::has_geometry_config() const {
  return this != internal_default_instance() && geometry_config_ != NULL;
}
inline void BEVFusionConfig::clear_geometry_config() {
  if (GetArenaNoVirtual() == NULL && geometry_config_ != NULL) {
    delete geometry_config_;
  }
  geometry_config_ = NULL;
}
inline const ::bevfusion::GeometryConfig& BEVFusionConfig::_internal_geometry_config() const {
  return *geometry_config_;
}
inline const ::bevfusion::GeometryConfig& BEVFusionConfig::geometry_config() const {
  const ::bevfusion::GeometryConfig* p = geometry_config_;
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.geometry_config)
  return p != NULL ? *p : *reinterpret_cast<const ::bevfusion::GeometryConfig*>(
      &::bevfusion::_GeometryConfig_default_instance_);
}
inline ::bevfusion::GeometryConfig* BEVFusionConfig::release_geometry_config() {
  // @@protoc_insertion_point(field_release:bevfusion.BEVFusionConfig.geometry_config)
  
  ::bevfusion::GeometryConfig* temp = geometry_config_;
  geometry_config_ = NULL;
  return temp;
}
inline ::bevfusion::GeometryConfig* BEVFusionConfig::mutable_geometry_config() {
  
  if (geometry_config_ == NULL) {
    auto* p = CreateMaybeMessage<::bevfusion::GeometryConfig>(GetArenaNoVirtual());
    geometry_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.geometry_config)
  return geometry_config_;
}
inline void BEVFusionConfig::set_allocated_geometry_config(::bevfusion::GeometryConfig* geometry_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete geometry_config_;
  }
  if (geometry_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      geometry_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, geometry_config, submessage_arena);
    }
    
  } else {
    
  }
  geometry_config_ = geometry_config;
  // @@protoc_insertion_point(field_set_allocated:bevfusion.BEVFusionConfig.geometry_config)
}

// .bevfusion.PostprocessorConfig postprocessor_config = 9;
inline bool BEVFusionConfig::has_postprocessor_config() const {
  return this != internal_default_instance() && postprocessor_config_ != NULL;
}
inline void BEVFusionConfig::clear_postprocessor_config() {
  if (GetArenaNoVirtual() == NULL && postprocessor_config_ != NULL) {
    delete postprocessor_config_;
  }
  postprocessor_config_ = NULL;
}
inline const ::bevfusion::PostprocessorConfig& BEVFusionConfig::_internal_postprocessor_config() const {
  return *postprocessor_config_;
}
inline const ::bevfusion::PostprocessorConfig& BEVFusionConfig::postprocessor_config() const {
  const ::bevfusion::PostprocessorConfig* p = postprocessor_config_;
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.postprocessor_config)
  return p != NULL ? *p : *reinterpret_cast<const ::bevfusion::PostprocessorConfig*>(
      &::bevfusion::_PostprocessorConfig_default_instance_);
}
inline ::bevfusion::PostprocessorConfig* BEVFusionConfig::release_postprocessor_config() {
  // @@protoc_insertion_point(field_release:bevfusion.BEVFusionConfig.postprocessor_config)
  
  ::bevfusion::PostprocessorConfig* temp = postprocessor_config_;
  postprocessor_config_ = NULL;
  return temp;
}
inline ::bevfusion::PostprocessorConfig* BEVFusionConfig::mutable_postprocessor_config() {
  
  if (postprocessor_config_ == NULL) {
    auto* p = CreateMaybeMessage<::bevfusion::PostprocessorConfig>(GetArenaNoVirtual());
    postprocessor_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.postprocessor_config)
  return postprocessor_config_;
}
inline void BEVFusionConfig::set_allocated_postprocessor_config(::bevfusion::PostprocessorConfig* postprocessor_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete postprocessor_config_;
  }
  if (postprocessor_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      postprocessor_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, postprocessor_config, submessage_arena);
    }
    
  } else {
    
  }
  postprocessor_config_ = postprocessor_config;
  // @@protoc_insertion_point(field_set_allocated:bevfusion.BEVFusionConfig.postprocessor_config)
}

// .bevfusion.ModelPaths model_paths = 10;
inline bool BEVFusionConfig::has_model_paths() const {
  return this != internal_default_instance() && model_paths_ != NULL;
}
inline void BEVFusionConfig::clear_model_paths() {
  if (GetArenaNoVirtual() == NULL && model_paths_ != NULL) {
    delete model_paths_;
  }
  model_paths_ = NULL;
}
inline const ::bevfusion::ModelPaths& BEVFusionConfig::_internal_model_paths() const {
  return *model_paths_;
}
inline const ::bevfusion::ModelPaths& BEVFusionConfig::model_paths() const {
  const ::bevfusion::ModelPaths* p = model_paths_;
  // @@protoc_insertion_point(field_get:bevfusion.BEVFusionConfig.model_paths)
  return p != NULL ? *p : *reinterpret_cast<const ::bevfusion::ModelPaths*>(
      &::bevfusion::_ModelPaths_default_instance_);
}
inline ::bevfusion::ModelPaths* BEVFusionConfig::release_model_paths() {
  // @@protoc_insertion_point(field_release:bevfusion.BEVFusionConfig.model_paths)
  
  ::bevfusion::ModelPaths* temp = model_paths_;
  model_paths_ = NULL;
  return temp;
}
inline ::bevfusion::ModelPaths* BEVFusionConfig::mutable_model_paths() {
  
  if (model_paths_ == NULL) {
    auto* p = CreateMaybeMessage<::bevfusion::ModelPaths>(GetArenaNoVirtual());
    model_paths_ = p;
  }
  // @@protoc_insertion_point(field_mutable:bevfusion.BEVFusionConfig.model_paths)
  return model_paths_;
}
inline void BEVFusionConfig::set_allocated_model_paths(::bevfusion::ModelPaths* model_paths) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete model_paths_;
  }
  if (model_paths) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      model_paths = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, model_paths, submessage_arena);
    }
    
  } else {
    
  }
  model_paths_ = model_paths;
  // @@protoc_insertion_point(field_set_allocated:bevfusion.BEVFusionConfig.model_paths)
}

// -------------------------------------------------------------------

// LidarConfig

// repeated float min_range = 1;
inline int LidarConfig::min_range_size() const {
  return min_range_.size();
}
inline void LidarConfig::clear_min_range() {
  min_range_.Clear();
}
inline float LidarConfig::min_range(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.min_range)
  return min_range_.Get(index);
}
inline void LidarConfig::set_min_range(int index, float value) {
  min_range_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.min_range)
}
inline void LidarConfig::add_min_range(float value) {
  min_range_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.LidarConfig.min_range)
}
inline const ::google::protobuf::RepeatedField< float >&
LidarConfig::min_range() const {
  // @@protoc_insertion_point(field_list:bevfusion.LidarConfig.min_range)
  return min_range_;
}
inline ::google::protobuf::RepeatedField< float >*
LidarConfig::mutable_min_range() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.LidarConfig.min_range)
  return &min_range_;
}

// repeated float max_range = 2;
inline int LidarConfig::max_range_size() const {
  return max_range_.size();
}
inline void LidarConfig::clear_max_range() {
  max_range_.Clear();
}
inline float LidarConfig::max_range(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.max_range)
  return max_range_.Get(index);
}
inline void LidarConfig::set_max_range(int index, float value) {
  max_range_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.max_range)
}
inline void LidarConfig::add_max_range(float value) {
  max_range_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.LidarConfig.max_range)
}
inline const ::google::protobuf::RepeatedField< float >&
LidarConfig::max_range() const {
  // @@protoc_insertion_point(field_list:bevfusion.LidarConfig.max_range)
  return max_range_;
}
inline ::google::protobuf::RepeatedField< float >*
LidarConfig::mutable_max_range() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.LidarConfig.max_range)
  return &max_range_;
}

// repeated float voxel_size = 3;
inline int LidarConfig::voxel_size_size() const {
  return voxel_size_.size();
}
inline void LidarConfig::clear_voxel_size() {
  voxel_size_.Clear();
}
inline float LidarConfig::voxel_size(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.voxel_size)
  return voxel_size_.Get(index);
}
inline void LidarConfig::set_voxel_size(int index, float value) {
  voxel_size_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.voxel_size)
}
inline void LidarConfig::add_voxel_size(float value) {
  voxel_size_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.LidarConfig.voxel_size)
}
inline const ::google::protobuf::RepeatedField< float >&
LidarConfig::voxel_size() const {
  // @@protoc_insertion_point(field_list:bevfusion.LidarConfig.voxel_size)
  return voxel_size_;
}
inline ::google::protobuf::RepeatedField< float >*
LidarConfig::mutable_voxel_size() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.LidarConfig.voxel_size)
  return &voxel_size_;
}

// repeated float grid_size = 4;
inline int LidarConfig::grid_size_size() const {
  return grid_size_.size();
}
inline void LidarConfig::clear_grid_size() {
  grid_size_.Clear();
}
inline float LidarConfig::grid_size(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.grid_size)
  return grid_size_.Get(index);
}
inline void LidarConfig::set_grid_size(int index, float value) {
  grid_size_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.grid_size)
}
inline void LidarConfig::add_grid_size(float value) {
  grid_size_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.LidarConfig.grid_size)
}
inline const ::google::protobuf::RepeatedField< float >&
LidarConfig::grid_size() const {
  // @@protoc_insertion_point(field_list:bevfusion.LidarConfig.grid_size)
  return grid_size_;
}
inline ::google::protobuf::RepeatedField< float >*
LidarConfig::mutable_grid_size() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.LidarConfig.grid_size)
  return &grid_size_;
}

// uint32 max_points_per_voxel = 5;
inline void LidarConfig::clear_max_points_per_voxel() {
  max_points_per_voxel_ = 0u;
}
inline ::google::protobuf::uint32 LidarConfig::max_points_per_voxel() const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.max_points_per_voxel)
  return max_points_per_voxel_;
}
inline void LidarConfig::set_max_points_per_voxel(::google::protobuf::uint32 value) {
  
  max_points_per_voxel_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.max_points_per_voxel)
}

// uint32 max_points = 6;
inline void LidarConfig::clear_max_points() {
  max_points_ = 0u;
}
inline ::google::protobuf::uint32 LidarConfig::max_points() const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.max_points)
  return max_points_;
}
inline void LidarConfig::set_max_points(::google::protobuf::uint32 value) {
  
  max_points_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.max_points)
}

// uint32 max_voxels = 7;
inline void LidarConfig::clear_max_voxels() {
  max_voxels_ = 0u;
}
inline ::google::protobuf::uint32 LidarConfig::max_voxels() const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.max_voxels)
  return max_voxels_;
}
inline void LidarConfig::set_max_voxels(::google::protobuf::uint32 value) {
  
  max_voxels_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.max_voxels)
}

// uint32 num_feature = 8;
inline void LidarConfig::clear_num_feature() {
  num_feature_ = 0u;
}
inline ::google::protobuf::uint32 LidarConfig::num_feature() const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.num_feature)
  return num_feature_;
}
inline void LidarConfig::set_num_feature(::google::protobuf::uint32 value) {
  
  num_feature_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.num_feature)
}

// string lidar_model_path = 9;
inline void LidarConfig::clear_lidar_model_path() {
  lidar_model_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LidarConfig::lidar_model_path() const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.lidar_model_path)
  return lidar_model_path_.GetNoArena();
}
inline void LidarConfig::set_lidar_model_path(const ::std::string& value) {
  
  lidar_model_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.lidar_model_path)
}
#if LANG_CXX11
inline void LidarConfig::set_lidar_model_path(::std::string&& value) {
  
  lidar_model_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.LidarConfig.lidar_model_path)
}
#endif
inline void LidarConfig::set_lidar_model_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  lidar_model_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.LidarConfig.lidar_model_path)
}
inline void LidarConfig::set_lidar_model_path(const char* value, size_t size) {
  
  lidar_model_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.LidarConfig.lidar_model_path)
}
inline ::std::string* LidarConfig::mutable_lidar_model_path() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.LidarConfig.lidar_model_path)
  return lidar_model_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LidarConfig::release_lidar_model_path() {
  // @@protoc_insertion_point(field_release:bevfusion.LidarConfig.lidar_model_path)
  
  return lidar_model_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LidarConfig::set_allocated_lidar_model_path(::std::string* lidar_model_path) {
  if (lidar_model_path != NULL) {
    
  } else {
    
  }
  lidar_model_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), lidar_model_path);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.LidarConfig.lidar_model_path)
}

// string coordinate_order = 10;
inline void LidarConfig::clear_coordinate_order() {
  coordinate_order_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LidarConfig::coordinate_order() const {
  // @@protoc_insertion_point(field_get:bevfusion.LidarConfig.coordinate_order)
  return coordinate_order_.GetNoArena();
}
inline void LidarConfig::set_coordinate_order(const ::std::string& value) {
  
  coordinate_order_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.LidarConfig.coordinate_order)
}
#if LANG_CXX11
inline void LidarConfig::set_coordinate_order(::std::string&& value) {
  
  coordinate_order_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.LidarConfig.coordinate_order)
}
#endif
inline void LidarConfig::set_coordinate_order(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  coordinate_order_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.LidarConfig.coordinate_order)
}
inline void LidarConfig::set_coordinate_order(const char* value, size_t size) {
  
  coordinate_order_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.LidarConfig.coordinate_order)
}
inline ::std::string* LidarConfig::mutable_coordinate_order() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.LidarConfig.coordinate_order)
  return coordinate_order_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LidarConfig::release_coordinate_order() {
  // @@protoc_insertion_point(field_release:bevfusion.LidarConfig.coordinate_order)
  
  return coordinate_order_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LidarConfig::set_allocated_coordinate_order(::std::string* coordinate_order) {
  if (coordinate_order != NULL) {
    
  } else {
    
  }
  coordinate_order_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), coordinate_order);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.LidarConfig.coordinate_order)
}

// -------------------------------------------------------------------

// GeometryConfig

// repeated float xbound = 1;
inline int GeometryConfig::xbound_size() const {
  return xbound_.size();
}
inline void GeometryConfig::clear_xbound() {
  xbound_.Clear();
}
inline float GeometryConfig::xbound(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.xbound)
  return xbound_.Get(index);
}
inline void GeometryConfig::set_xbound(int index, float value) {
  xbound_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.xbound)
}
inline void GeometryConfig::add_xbound(float value) {
  xbound_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.GeometryConfig.xbound)
}
inline const ::google::protobuf::RepeatedField< float >&
GeometryConfig::xbound() const {
  // @@protoc_insertion_point(field_list:bevfusion.GeometryConfig.xbound)
  return xbound_;
}
inline ::google::protobuf::RepeatedField< float >*
GeometryConfig::mutable_xbound() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.GeometryConfig.xbound)
  return &xbound_;
}

// repeated float ybound = 2;
inline int GeometryConfig::ybound_size() const {
  return ybound_.size();
}
inline void GeometryConfig::clear_ybound() {
  ybound_.Clear();
}
inline float GeometryConfig::ybound(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.ybound)
  return ybound_.Get(index);
}
inline void GeometryConfig::set_ybound(int index, float value) {
  ybound_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.ybound)
}
inline void GeometryConfig::add_ybound(float value) {
  ybound_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.GeometryConfig.ybound)
}
inline const ::google::protobuf::RepeatedField< float >&
GeometryConfig::ybound() const {
  // @@protoc_insertion_point(field_list:bevfusion.GeometryConfig.ybound)
  return ybound_;
}
inline ::google::protobuf::RepeatedField< float >*
GeometryConfig::mutable_ybound() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.GeometryConfig.ybound)
  return &ybound_;
}

// repeated float zbound = 3;
inline int GeometryConfig::zbound_size() const {
  return zbound_.size();
}
inline void GeometryConfig::clear_zbound() {
  zbound_.Clear();
}
inline float GeometryConfig::zbound(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.zbound)
  return zbound_.Get(index);
}
inline void GeometryConfig::set_zbound(int index, float value) {
  zbound_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.zbound)
}
inline void GeometryConfig::add_zbound(float value) {
  zbound_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.GeometryConfig.zbound)
}
inline const ::google::protobuf::RepeatedField< float >&
GeometryConfig::zbound() const {
  // @@protoc_insertion_point(field_list:bevfusion.GeometryConfig.zbound)
  return zbound_;
}
inline ::google::protobuf::RepeatedField< float >*
GeometryConfig::mutable_zbound() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.GeometryConfig.zbound)
  return &zbound_;
}

// repeated float dbound = 4;
inline int GeometryConfig::dbound_size() const {
  return dbound_.size();
}
inline void GeometryConfig::clear_dbound() {
  dbound_.Clear();
}
inline float GeometryConfig::dbound(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.dbound)
  return dbound_.Get(index);
}
inline void GeometryConfig::set_dbound(int index, float value) {
  dbound_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.dbound)
}
inline void GeometryConfig::add_dbound(float value) {
  dbound_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.GeometryConfig.dbound)
}
inline const ::google::protobuf::RepeatedField< float >&
GeometryConfig::dbound() const {
  // @@protoc_insertion_point(field_list:bevfusion.GeometryConfig.dbound)
  return dbound_;
}
inline ::google::protobuf::RepeatedField< float >*
GeometryConfig::mutable_dbound() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.GeometryConfig.dbound)
  return &dbound_;
}

// uint32 image_width = 5;
inline void GeometryConfig::clear_image_width() {
  image_width_ = 0u;
}
inline ::google::protobuf::uint32 GeometryConfig::image_width() const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.image_width)
  return image_width_;
}
inline void GeometryConfig::set_image_width(::google::protobuf::uint32 value) {
  
  image_width_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.image_width)
}

// uint32 image_height = 6;
inline void GeometryConfig::clear_image_height() {
  image_height_ = 0u;
}
inline ::google::protobuf::uint32 GeometryConfig::image_height() const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.image_height)
  return image_height_;
}
inline void GeometryConfig::set_image_height(::google::protobuf::uint32 value) {
  
  image_height_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.image_height)
}

// uint32 feat_width = 7;
inline void GeometryConfig::clear_feat_width() {
  feat_width_ = 0u;
}
inline ::google::protobuf::uint32 GeometryConfig::feat_width() const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.feat_width)
  return feat_width_;
}
inline void GeometryConfig::set_feat_width(::google::protobuf::uint32 value) {
  
  feat_width_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.feat_width)
}

// uint32 feat_height = 8;
inline void GeometryConfig::clear_feat_height() {
  feat_height_ = 0u;
}
inline ::google::protobuf::uint32 GeometryConfig::feat_height() const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.feat_height)
  return feat_height_;
}
inline void GeometryConfig::set_feat_height(::google::protobuf::uint32 value) {
  
  feat_height_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.feat_height)
}

// uint32 num_camera = 9;
inline void GeometryConfig::clear_num_camera() {
  num_camera_ = 0u;
}
inline ::google::protobuf::uint32 GeometryConfig::num_camera() const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.num_camera)
  return num_camera_;
}
inline void GeometryConfig::set_num_camera(::google::protobuf::uint32 value) {
  
  num_camera_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.num_camera)
}

// repeated uint32 geometry_dim = 10;
inline int GeometryConfig::geometry_dim_size() const {
  return geometry_dim_.size();
}
inline void GeometryConfig::clear_geometry_dim() {
  geometry_dim_.Clear();
}
inline ::google::protobuf::uint32 GeometryConfig::geometry_dim(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.GeometryConfig.geometry_dim)
  return geometry_dim_.Get(index);
}
inline void GeometryConfig::set_geometry_dim(int index, ::google::protobuf::uint32 value) {
  geometry_dim_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.GeometryConfig.geometry_dim)
}
inline void GeometryConfig::add_geometry_dim(::google::protobuf::uint32 value) {
  geometry_dim_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.GeometryConfig.geometry_dim)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
GeometryConfig::geometry_dim() const {
  // @@protoc_insertion_point(field_list:bevfusion.GeometryConfig.geometry_dim)
  return geometry_dim_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
GeometryConfig::mutable_geometry_dim() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.GeometryConfig.geometry_dim)
  return &geometry_dim_;
}

// -------------------------------------------------------------------

// PostprocessorConfig

// uint32 out_size_factor = 1;
inline void PostprocessorConfig::clear_out_size_factor() {
  out_size_factor_ = 0u;
}
inline ::google::protobuf::uint32 PostprocessorConfig::out_size_factor() const {
  // @@protoc_insertion_point(field_get:bevfusion.PostprocessorConfig.out_size_factor)
  return out_size_factor_;
}
inline void PostprocessorConfig::set_out_size_factor(::google::protobuf::uint32 value) {
  
  out_size_factor_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.PostprocessorConfig.out_size_factor)
}

// repeated float pc_range = 2;
inline int PostprocessorConfig::pc_range_size() const {
  return pc_range_.size();
}
inline void PostprocessorConfig::clear_pc_range() {
  pc_range_.Clear();
}
inline float PostprocessorConfig::pc_range(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.PostprocessorConfig.pc_range)
  return pc_range_.Get(index);
}
inline void PostprocessorConfig::set_pc_range(int index, float value) {
  pc_range_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.PostprocessorConfig.pc_range)
}
inline void PostprocessorConfig::add_pc_range(float value) {
  pc_range_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.PostprocessorConfig.pc_range)
}
inline const ::google::protobuf::RepeatedField< float >&
PostprocessorConfig::pc_range() const {
  // @@protoc_insertion_point(field_list:bevfusion.PostprocessorConfig.pc_range)
  return pc_range_;
}
inline ::google::protobuf::RepeatedField< float >*
PostprocessorConfig::mutable_pc_range() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.PostprocessorConfig.pc_range)
  return &pc_range_;
}

// repeated float post_center_range_start = 3;
inline int PostprocessorConfig::post_center_range_start_size() const {
  return post_center_range_start_.size();
}
inline void PostprocessorConfig::clear_post_center_range_start() {
  post_center_range_start_.Clear();
}
inline float PostprocessorConfig::post_center_range_start(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.PostprocessorConfig.post_center_range_start)
  return post_center_range_start_.Get(index);
}
inline void PostprocessorConfig::set_post_center_range_start(int index, float value) {
  post_center_range_start_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.PostprocessorConfig.post_center_range_start)
}
inline void PostprocessorConfig::add_post_center_range_start(float value) {
  post_center_range_start_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.PostprocessorConfig.post_center_range_start)
}
inline const ::google::protobuf::RepeatedField< float >&
PostprocessorConfig::post_center_range_start() const {
  // @@protoc_insertion_point(field_list:bevfusion.PostprocessorConfig.post_center_range_start)
  return post_center_range_start_;
}
inline ::google::protobuf::RepeatedField< float >*
PostprocessorConfig::mutable_post_center_range_start() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.PostprocessorConfig.post_center_range_start)
  return &post_center_range_start_;
}

// repeated float post_center_range_end = 4;
inline int PostprocessorConfig::post_center_range_end_size() const {
  return post_center_range_end_.size();
}
inline void PostprocessorConfig::clear_post_center_range_end() {
  post_center_range_end_.Clear();
}
inline float PostprocessorConfig::post_center_range_end(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.PostprocessorConfig.post_center_range_end)
  return post_center_range_end_.Get(index);
}
inline void PostprocessorConfig::set_post_center_range_end(int index, float value) {
  post_center_range_end_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.PostprocessorConfig.post_center_range_end)
}
inline void PostprocessorConfig::add_post_center_range_end(float value) {
  post_center_range_end_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.PostprocessorConfig.post_center_range_end)
}
inline const ::google::protobuf::RepeatedField< float >&
PostprocessorConfig::post_center_range_end() const {
  // @@protoc_insertion_point(field_list:bevfusion.PostprocessorConfig.post_center_range_end)
  return post_center_range_end_;
}
inline ::google::protobuf::RepeatedField< float >*
PostprocessorConfig::mutable_post_center_range_end() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.PostprocessorConfig.post_center_range_end)
  return &post_center_range_end_;
}

// repeated float voxel_size = 5;
inline int PostprocessorConfig::voxel_size_size() const {
  return voxel_size_.size();
}
inline void PostprocessorConfig::clear_voxel_size() {
  voxel_size_.Clear();
}
inline float PostprocessorConfig::voxel_size(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.PostprocessorConfig.voxel_size)
  return voxel_size_.Get(index);
}
inline void PostprocessorConfig::set_voxel_size(int index, float value) {
  voxel_size_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.PostprocessorConfig.voxel_size)
}
inline void PostprocessorConfig::add_voxel_size(float value) {
  voxel_size_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.PostprocessorConfig.voxel_size)
}
inline const ::google::protobuf::RepeatedField< float >&
PostprocessorConfig::voxel_size() const {
  // @@protoc_insertion_point(field_list:bevfusion.PostprocessorConfig.voxel_size)
  return voxel_size_;
}
inline ::google::protobuf::RepeatedField< float >*
PostprocessorConfig::mutable_voxel_size() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.PostprocessorConfig.voxel_size)
  return &voxel_size_;
}

// bool sorted_bboxes = 6;
inline void PostprocessorConfig::clear_sorted_bboxes() {
  sorted_bboxes_ = false;
}
inline bool PostprocessorConfig::sorted_bboxes() const {
  // @@protoc_insertion_point(field_get:bevfusion.PostprocessorConfig.sorted_bboxes)
  return sorted_bboxes_;
}
inline void PostprocessorConfig::set_sorted_bboxes(bool value) {
  
  sorted_bboxes_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.PostprocessorConfig.sorted_bboxes)
}

// -------------------------------------------------------------------

// ModelPaths

// string camera_backbone_path = 1;
inline void ModelPaths::clear_camera_backbone_path() {
  camera_backbone_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModelPaths::camera_backbone_path() const {
  // @@protoc_insertion_point(field_get:bevfusion.ModelPaths.camera_backbone_path)
  return camera_backbone_path_.GetNoArena();
}
inline void ModelPaths::set_camera_backbone_path(const ::std::string& value) {
  
  camera_backbone_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.ModelPaths.camera_backbone_path)
}
#if LANG_CXX11
inline void ModelPaths::set_camera_backbone_path(::std::string&& value) {
  
  camera_backbone_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.ModelPaths.camera_backbone_path)
}
#endif
inline void ModelPaths::set_camera_backbone_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  camera_backbone_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.ModelPaths.camera_backbone_path)
}
inline void ModelPaths::set_camera_backbone_path(const char* value, size_t size) {
  
  camera_backbone_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.ModelPaths.camera_backbone_path)
}
inline ::std::string* ModelPaths::mutable_camera_backbone_path() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.ModelPaths.camera_backbone_path)
  return camera_backbone_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModelPaths::release_camera_backbone_path() {
  // @@protoc_insertion_point(field_release:bevfusion.ModelPaths.camera_backbone_path)
  
  return camera_backbone_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModelPaths::set_allocated_camera_backbone_path(::std::string* camera_backbone_path) {
  if (camera_backbone_path != NULL) {
    
  } else {
    
  }
  camera_backbone_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_backbone_path);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.ModelPaths.camera_backbone_path)
}

// string lidar_backbone_path = 2;
inline void ModelPaths::clear_lidar_backbone_path() {
  lidar_backbone_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModelPaths::lidar_backbone_path() const {
  // @@protoc_insertion_point(field_get:bevfusion.ModelPaths.lidar_backbone_path)
  return lidar_backbone_path_.GetNoArena();
}
inline void ModelPaths::set_lidar_backbone_path(const ::std::string& value) {
  
  lidar_backbone_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.ModelPaths.lidar_backbone_path)
}
#if LANG_CXX11
inline void ModelPaths::set_lidar_backbone_path(::std::string&& value) {
  
  lidar_backbone_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.ModelPaths.lidar_backbone_path)
}
#endif
inline void ModelPaths::set_lidar_backbone_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  lidar_backbone_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.ModelPaths.lidar_backbone_path)
}
inline void ModelPaths::set_lidar_backbone_path(const char* value, size_t size) {
  
  lidar_backbone_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.ModelPaths.lidar_backbone_path)
}
inline ::std::string* ModelPaths::mutable_lidar_backbone_path() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.ModelPaths.lidar_backbone_path)
  return lidar_backbone_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModelPaths::release_lidar_backbone_path() {
  // @@protoc_insertion_point(field_release:bevfusion.ModelPaths.lidar_backbone_path)
  
  return lidar_backbone_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModelPaths::set_allocated_lidar_backbone_path(::std::string* lidar_backbone_path) {
  if (lidar_backbone_path != NULL) {
    
  } else {
    
  }
  lidar_backbone_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), lidar_backbone_path);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.ModelPaths.lidar_backbone_path)
}

// string fuser_path = 3;
inline void ModelPaths::clear_fuser_path() {
  fuser_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModelPaths::fuser_path() const {
  // @@protoc_insertion_point(field_get:bevfusion.ModelPaths.fuser_path)
  return fuser_path_.GetNoArena();
}
inline void ModelPaths::set_fuser_path(const ::std::string& value) {
  
  fuser_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.ModelPaths.fuser_path)
}
#if LANG_CXX11
inline void ModelPaths::set_fuser_path(::std::string&& value) {
  
  fuser_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.ModelPaths.fuser_path)
}
#endif
inline void ModelPaths::set_fuser_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  fuser_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.ModelPaths.fuser_path)
}
inline void ModelPaths::set_fuser_path(const char* value, size_t size) {
  
  fuser_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.ModelPaths.fuser_path)
}
inline ::std::string* ModelPaths::mutable_fuser_path() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.ModelPaths.fuser_path)
  return fuser_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModelPaths::release_fuser_path() {
  // @@protoc_insertion_point(field_release:bevfusion.ModelPaths.fuser_path)
  
  return fuser_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModelPaths::set_allocated_fuser_path(::std::string* fuser_path) {
  if (fuser_path != NULL) {
    
  } else {
    
  }
  fuser_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fuser_path);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.ModelPaths.fuser_path)
}

// string head_bbox_path = 4;
inline void ModelPaths::clear_head_bbox_path() {
  head_bbox_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModelPaths::head_bbox_path() const {
  // @@protoc_insertion_point(field_get:bevfusion.ModelPaths.head_bbox_path)
  return head_bbox_path_.GetNoArena();
}
inline void ModelPaths::set_head_bbox_path(const ::std::string& value) {
  
  head_bbox_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.ModelPaths.head_bbox_path)
}
#if LANG_CXX11
inline void ModelPaths::set_head_bbox_path(::std::string&& value) {
  
  head_bbox_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.ModelPaths.head_bbox_path)
}
#endif
inline void ModelPaths::set_head_bbox_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  head_bbox_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.ModelPaths.head_bbox_path)
}
inline void ModelPaths::set_head_bbox_path(const char* value, size_t size) {
  
  head_bbox_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.ModelPaths.head_bbox_path)
}
inline ::std::string* ModelPaths::mutable_head_bbox_path() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.ModelPaths.head_bbox_path)
  return head_bbox_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModelPaths::release_head_bbox_path() {
  // @@protoc_insertion_point(field_release:bevfusion.ModelPaths.head_bbox_path)
  
  return head_bbox_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModelPaths::set_allocated_head_bbox_path(::std::string* head_bbox_path) {
  if (head_bbox_path != NULL) {
    
  } else {
    
  }
  head_bbox_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), head_bbox_path);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.ModelPaths.head_bbox_path)
}

// string camera_vtransform_path = 5;
inline void ModelPaths::clear_camera_vtransform_path() {
  camera_vtransform_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModelPaths::camera_vtransform_path() const {
  // @@protoc_insertion_point(field_get:bevfusion.ModelPaths.camera_vtransform_path)
  return camera_vtransform_path_.GetNoArena();
}
inline void ModelPaths::set_camera_vtransform_path(const ::std::string& value) {
  
  camera_vtransform_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.ModelPaths.camera_vtransform_path)
}
#if LANG_CXX11
inline void ModelPaths::set_camera_vtransform_path(::std::string&& value) {
  
  camera_vtransform_path_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.ModelPaths.camera_vtransform_path)
}
#endif
inline void ModelPaths::set_camera_vtransform_path(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  camera_vtransform_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.ModelPaths.camera_vtransform_path)
}
inline void ModelPaths::set_camera_vtransform_path(const char* value, size_t size) {
  
  camera_vtransform_path_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.ModelPaths.camera_vtransform_path)
}
inline ::std::string* ModelPaths::mutable_camera_vtransform_path() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.ModelPaths.camera_vtransform_path)
  return camera_vtransform_path_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModelPaths::release_camera_vtransform_path() {
  // @@protoc_insertion_point(field_release:bevfusion.ModelPaths.camera_vtransform_path)
  
  return camera_vtransform_path_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModelPaths::set_allocated_camera_vtransform_path(::std::string* camera_vtransform_path) {
  if (camera_vtransform_path != NULL) {
    
  } else {
    
  }
  camera_vtransform_path_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), camera_vtransform_path);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.ModelPaths.camera_vtransform_path)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bevfusion

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_BEVFusionConfig_2eproto
