// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraConfig.proto

#include "CameraConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace bevfusion {
class CameraConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CameraConfig>
      _instance;
} _CameraConfig_default_instance_;
}  // namespace bevfusion
namespace protobuf_CameraConfig_2eproto {
static void InitDefaultsCameraConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bevfusion::_CameraConfig_default_instance_;
    new (ptr) ::bevfusion::CameraConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bevfusion::CameraConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CameraConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCameraConfig}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CameraConfig.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, intrinsics_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, camera2lidar_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, lidar2image_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, img_aug_matrix_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, image_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, image_height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, output_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, output_height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, resize_lim_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, mean_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, std_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, scale_factor_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, offset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bevfusion::CameraConfig, interpolation_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::bevfusion::CameraConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::bevfusion::_CameraConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "CameraConfig.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022CameraConfig.proto\022\tbevfusion\"\251\002\n\014Came"
      "raConfig\022\022\n\nintrinsics\030\001 \003(\002\022\024\n\014camera2l"
      "idar\030\002 \003(\002\022\023\n\013lidar2image\030\003 \003(\002\022\026\n\016img_a"
      "ug_matrix\030\004 \003(\002\022\023\n\013image_width\030\005 \001(\r\022\024\n\014"
      "image_height\030\006 \001(\r\022\024\n\014output_width\030\007 \001(\r"
      "\022\025\n\routput_height\030\010 \001(\r\022\022\n\nresize_lim\030\t "
      "\001(\002\022\014\n\004mean\030\n \003(\002\022\013\n\003std\030\013 \003(\002\022\024\n\014scale_"
      "factor\030\014 \001(\002\022\016\n\006offset\030\r \001(\002\022\025\n\rinterpol"
      "ation\030\016 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 339);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CameraConfig.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_CameraConfig_2eproto
namespace bevfusion {

// ===================================================================

void CameraConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CameraConfig::kIntrinsicsFieldNumber;
const int CameraConfig::kCamera2LidarFieldNumber;
const int CameraConfig::kLidar2ImageFieldNumber;
const int CameraConfig::kImgAugMatrixFieldNumber;
const int CameraConfig::kImageWidthFieldNumber;
const int CameraConfig::kImageHeightFieldNumber;
const int CameraConfig::kOutputWidthFieldNumber;
const int CameraConfig::kOutputHeightFieldNumber;
const int CameraConfig::kResizeLimFieldNumber;
const int CameraConfig::kMeanFieldNumber;
const int CameraConfig::kStdFieldNumber;
const int CameraConfig::kScaleFactorFieldNumber;
const int CameraConfig::kOffsetFieldNumber;
const int CameraConfig::kInterpolationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CameraConfig::CameraConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_CameraConfig_2eproto::scc_info_CameraConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bevfusion.CameraConfig)
}
CameraConfig::CameraConfig(const CameraConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      intrinsics_(from.intrinsics_),
      camera2lidar_(from.camera2lidar_),
      lidar2image_(from.lidar2image_),
      img_aug_matrix_(from.img_aug_matrix_),
      mean_(from.mean_),
      std_(from.std_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  interpolation_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.interpolation().size() > 0) {
    interpolation_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.interpolation_);
  }
  ::memcpy(&image_width_, &from.image_width_,
    static_cast<size_t>(reinterpret_cast<char*>(&offset_) -
    reinterpret_cast<char*>(&image_width_)) + sizeof(offset_));
  // @@protoc_insertion_point(copy_constructor:bevfusion.CameraConfig)
}

void CameraConfig::SharedCtor() {
  interpolation_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&image_width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&offset_) -
      reinterpret_cast<char*>(&image_width_)) + sizeof(offset_));
}

CameraConfig::~CameraConfig() {
  // @@protoc_insertion_point(destructor:bevfusion.CameraConfig)
  SharedDtor();
}

void CameraConfig::SharedDtor() {
  interpolation_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CameraConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CameraConfig::descriptor() {
  ::protobuf_CameraConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_CameraConfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CameraConfig& CameraConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_CameraConfig_2eproto::scc_info_CameraConfig.base);
  return *internal_default_instance();
}


void CameraConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:bevfusion.CameraConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  intrinsics_.Clear();
  camera2lidar_.Clear();
  lidar2image_.Clear();
  img_aug_matrix_.Clear();
  mean_.Clear();
  std_.Clear();
  interpolation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&image_width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&offset_) -
      reinterpret_cast<char*>(&image_width_)) + sizeof(offset_));
  _internal_metadata_.Clear();
}

bool CameraConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bevfusion.CameraConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float intrinsics = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_intrinsics())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_intrinsics())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float camera2lidar = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_camera2lidar())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 18u, input, this->mutable_camera2lidar())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float lidar2image = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_lidar2image())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 26u, input, this->mutable_lidar2image())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float img_aug_matrix = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_img_aug_matrix())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 34u, input, this->mutable_img_aug_matrix())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 image_width = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &image_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 image_height = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &image_height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 output_width = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &output_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 output_height = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &output_height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float resize_lim = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(77u /* 77 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &resize_lim_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float mean = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_mean())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(85u /* 85 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 82u, input, this->mutable_mean())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float std = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_std())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(93u /* 93 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 90u, input, this->mutable_std())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float scale_factor = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(101u /* 101 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &scale_factor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float offset = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(109u /* 109 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &offset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string interpolation = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_interpolation()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->interpolation().data(), static_cast<int>(this->interpolation().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "bevfusion.CameraConfig.interpolation"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bevfusion.CameraConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bevfusion.CameraConfig)
  return false;
#undef DO_
}

void CameraConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bevfusion.CameraConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float intrinsics = 1;
  if (this->intrinsics_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _intrinsics_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->intrinsics().data(), this->intrinsics_size(), output);
  }

  // repeated float camera2lidar = 2;
  if (this->camera2lidar_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _camera2lidar_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->camera2lidar().data(), this->camera2lidar_size(), output);
  }

  // repeated float lidar2image = 3;
  if (this->lidar2image_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _lidar2image_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->lidar2image().data(), this->lidar2image_size(), output);
  }

  // repeated float img_aug_matrix = 4;
  if (this->img_aug_matrix_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _img_aug_matrix_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->img_aug_matrix().data(), this->img_aug_matrix_size(), output);
  }

  // uint32 image_width = 5;
  if (this->image_width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->image_width(), output);
  }

  // uint32 image_height = 6;
  if (this->image_height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->image_height(), output);
  }

  // uint32 output_width = 7;
  if (this->output_width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->output_width(), output);
  }

  // uint32 output_height = 8;
  if (this->output_height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->output_height(), output);
  }

  // float resize_lim = 9;
  if (this->resize_lim() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->resize_lim(), output);
  }

  // repeated float mean = 10;
  if (this->mean_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(10, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _mean_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->mean().data(), this->mean_size(), output);
  }

  // repeated float std = 11;
  if (this->std_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(11, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _std_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->std().data(), this->std_size(), output);
  }

  // float scale_factor = 12;
  if (this->scale_factor() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(12, this->scale_factor(), output);
  }

  // float offset = 13;
  if (this->offset() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(13, this->offset(), output);
  }

  // string interpolation = 14;
  if (this->interpolation().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->interpolation().data(), static_cast<int>(this->interpolation().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bevfusion.CameraConfig.interpolation");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->interpolation(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:bevfusion.CameraConfig)
}

::google::protobuf::uint8* CameraConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bevfusion.CameraConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float intrinsics = 1;
  if (this->intrinsics_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _intrinsics_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->intrinsics_, target);
  }

  // repeated float camera2lidar = 2;
  if (this->camera2lidar_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _camera2lidar_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->camera2lidar_, target);
  }

  // repeated float lidar2image = 3;
  if (this->lidar2image_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _lidar2image_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->lidar2image_, target);
  }

  // repeated float img_aug_matrix = 4;
  if (this->img_aug_matrix_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _img_aug_matrix_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->img_aug_matrix_, target);
  }

  // uint32 image_width = 5;
  if (this->image_width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->image_width(), target);
  }

  // uint32 image_height = 6;
  if (this->image_height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->image_height(), target);
  }

  // uint32 output_width = 7;
  if (this->output_width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->output_width(), target);
  }

  // uint32 output_height = 8;
  if (this->output_height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->output_height(), target);
  }

  // float resize_lim = 9;
  if (this->resize_lim() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->resize_lim(), target);
  }

  // repeated float mean = 10;
  if (this->mean_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      10,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _mean_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->mean_, target);
  }

  // repeated float std = 11;
  if (this->std_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      11,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _std_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->std_, target);
  }

  // float scale_factor = 12;
  if (this->scale_factor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(12, this->scale_factor(), target);
  }

  // float offset = 13;
  if (this->offset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(13, this->offset(), target);
  }

  // string interpolation = 14;
  if (this->interpolation().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->interpolation().data(), static_cast<int>(this->interpolation().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "bevfusion.CameraConfig.interpolation");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->interpolation(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bevfusion.CameraConfig)
  return target;
}

size_t CameraConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bevfusion.CameraConfig)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float intrinsics = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->intrinsics_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _intrinsics_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float camera2lidar = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->camera2lidar_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _camera2lidar_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float lidar2image = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->lidar2image_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _lidar2image_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float img_aug_matrix = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->img_aug_matrix_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _img_aug_matrix_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float mean = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->mean_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _mean_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float std = 11;
  {
    unsigned int count = static_cast<unsigned int>(this->std_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _std_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string interpolation = 14;
  if (this->interpolation().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->interpolation());
  }

  // uint32 image_width = 5;
  if (this->image_width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->image_width());
  }

  // uint32 image_height = 6;
  if (this->image_height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->image_height());
  }

  // uint32 output_width = 7;
  if (this->output_width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->output_width());
  }

  // uint32 output_height = 8;
  if (this->output_height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->output_height());
  }

  // float resize_lim = 9;
  if (this->resize_lim() != 0) {
    total_size += 1 + 4;
  }

  // float scale_factor = 12;
  if (this->scale_factor() != 0) {
    total_size += 1 + 4;
  }

  // float offset = 13;
  if (this->offset() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CameraConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bevfusion.CameraConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const CameraConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CameraConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bevfusion.CameraConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bevfusion.CameraConfig)
    MergeFrom(*source);
  }
}

void CameraConfig::MergeFrom(const CameraConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bevfusion.CameraConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  intrinsics_.MergeFrom(from.intrinsics_);
  camera2lidar_.MergeFrom(from.camera2lidar_);
  lidar2image_.MergeFrom(from.lidar2image_);
  img_aug_matrix_.MergeFrom(from.img_aug_matrix_);
  mean_.MergeFrom(from.mean_);
  std_.MergeFrom(from.std_);
  if (from.interpolation().size() > 0) {

    interpolation_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.interpolation_);
  }
  if (from.image_width() != 0) {
    set_image_width(from.image_width());
  }
  if (from.image_height() != 0) {
    set_image_height(from.image_height());
  }
  if (from.output_width() != 0) {
    set_output_width(from.output_width());
  }
  if (from.output_height() != 0) {
    set_output_height(from.output_height());
  }
  if (from.resize_lim() != 0) {
    set_resize_lim(from.resize_lim());
  }
  if (from.scale_factor() != 0) {
    set_scale_factor(from.scale_factor());
  }
  if (from.offset() != 0) {
    set_offset(from.offset());
  }
}

void CameraConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bevfusion.CameraConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CameraConfig::CopyFrom(const CameraConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bevfusion.CameraConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CameraConfig::IsInitialized() const {
  return true;
}

void CameraConfig::Swap(CameraConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CameraConfig::InternalSwap(CameraConfig* other) {
  using std::swap;
  intrinsics_.InternalSwap(&other->intrinsics_);
  camera2lidar_.InternalSwap(&other->camera2lidar_);
  lidar2image_.InternalSwap(&other->lidar2image_);
  img_aug_matrix_.InternalSwap(&other->img_aug_matrix_);
  mean_.InternalSwap(&other->mean_);
  std_.InternalSwap(&other->std_);
  interpolation_.Swap(&other->interpolation_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(image_width_, other->image_width_);
  swap(image_height_, other->image_height_);
  swap(output_width_, other->output_width_);
  swap(output_height_, other->output_height_);
  swap(resize_lim_, other->resize_lim_);
  swap(scale_factor_, other->scale_factor_);
  swap(offset_, other->offset_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CameraConfig::GetMetadata() const {
  protobuf_CameraConfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_CameraConfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bevfusion
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bevfusion::CameraConfig* Arena::CreateMaybeMessage< ::bevfusion::CameraConfig >(Arena* arena) {
  return Arena::CreateInternal< ::bevfusion::CameraConfig >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
