// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraConfig.proto

#ifndef PROTOBUF_INCLUDED_CameraConfig_2eproto
#define PROTOBUF_INCLUDED_CameraConfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_CameraConfig_2eproto 

namespace protobuf_CameraConfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_CameraConfig_2eproto
namespace bevfusion {
class CameraConfig;
class CameraConfigDefaultTypeInternal;
extern CameraConfigDefaultTypeInternal _CameraConfig_default_instance_;
}  // namespace bevfusion
namespace google {
namespace protobuf {
template<> ::bevfusion::CameraConfig* Arena::CreateMaybeMessage<::bevfusion::CameraConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bevfusion {

// ===================================================================

class CameraConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bevfusion.CameraConfig) */ {
 public:
  CameraConfig();
  virtual ~CameraConfig();

  CameraConfig(const CameraConfig& from);

  inline CameraConfig& operator=(const CameraConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CameraConfig(CameraConfig&& from) noexcept
    : CameraConfig() {
    *this = ::std::move(from);
  }

  inline CameraConfig& operator=(CameraConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CameraConfig* internal_default_instance() {
    return reinterpret_cast<const CameraConfig*>(
               &_CameraConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CameraConfig* other);
  friend void swap(CameraConfig& a, CameraConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CameraConfig* New() const final {
    return CreateMaybeMessage<CameraConfig>(NULL);
  }

  CameraConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CameraConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CameraConfig& from);
  void MergeFrom(const CameraConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CameraConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float intrinsics = 1;
  int intrinsics_size() const;
  void clear_intrinsics();
  static const int kIntrinsicsFieldNumber = 1;
  float intrinsics(int index) const;
  void set_intrinsics(int index, float value);
  void add_intrinsics(float value);
  const ::google::protobuf::RepeatedField< float >&
      intrinsics() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_intrinsics();

  // repeated float camera2lidar = 2;
  int camera2lidar_size() const;
  void clear_camera2lidar();
  static const int kCamera2LidarFieldNumber = 2;
  float camera2lidar(int index) const;
  void set_camera2lidar(int index, float value);
  void add_camera2lidar(float value);
  const ::google::protobuf::RepeatedField< float >&
      camera2lidar() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_camera2lidar();

  // repeated float lidar2image = 3;
  int lidar2image_size() const;
  void clear_lidar2image();
  static const int kLidar2ImageFieldNumber = 3;
  float lidar2image(int index) const;
  void set_lidar2image(int index, float value);
  void add_lidar2image(float value);
  const ::google::protobuf::RepeatedField< float >&
      lidar2image() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_lidar2image();

  // repeated float img_aug_matrix = 4;
  int img_aug_matrix_size() const;
  void clear_img_aug_matrix();
  static const int kImgAugMatrixFieldNumber = 4;
  float img_aug_matrix(int index) const;
  void set_img_aug_matrix(int index, float value);
  void add_img_aug_matrix(float value);
  const ::google::protobuf::RepeatedField< float >&
      img_aug_matrix() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_img_aug_matrix();

  // repeated float mean = 10;
  int mean_size() const;
  void clear_mean();
  static const int kMeanFieldNumber = 10;
  float mean(int index) const;
  void set_mean(int index, float value);
  void add_mean(float value);
  const ::google::protobuf::RepeatedField< float >&
      mean() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_mean();

  // repeated float std = 11;
  int std_size() const;
  void clear_std();
  static const int kStdFieldNumber = 11;
  float std(int index) const;
  void set_std(int index, float value);
  void add_std(float value);
  const ::google::protobuf::RepeatedField< float >&
      std() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_std();

  // string interpolation = 14;
  void clear_interpolation();
  static const int kInterpolationFieldNumber = 14;
  const ::std::string& interpolation() const;
  void set_interpolation(const ::std::string& value);
  #if LANG_CXX11
  void set_interpolation(::std::string&& value);
  #endif
  void set_interpolation(const char* value);
  void set_interpolation(const char* value, size_t size);
  ::std::string* mutable_interpolation();
  ::std::string* release_interpolation();
  void set_allocated_interpolation(::std::string* interpolation);

  // uint32 image_width = 5;
  void clear_image_width();
  static const int kImageWidthFieldNumber = 5;
  ::google::protobuf::uint32 image_width() const;
  void set_image_width(::google::protobuf::uint32 value);

  // uint32 image_height = 6;
  void clear_image_height();
  static const int kImageHeightFieldNumber = 6;
  ::google::protobuf::uint32 image_height() const;
  void set_image_height(::google::protobuf::uint32 value);

  // uint32 output_width = 7;
  void clear_output_width();
  static const int kOutputWidthFieldNumber = 7;
  ::google::protobuf::uint32 output_width() const;
  void set_output_width(::google::protobuf::uint32 value);

  // uint32 output_height = 8;
  void clear_output_height();
  static const int kOutputHeightFieldNumber = 8;
  ::google::protobuf::uint32 output_height() const;
  void set_output_height(::google::protobuf::uint32 value);

  // float resize_lim = 9;
  void clear_resize_lim();
  static const int kResizeLimFieldNumber = 9;
  float resize_lim() const;
  void set_resize_lim(float value);

  // float scale_factor = 12;
  void clear_scale_factor();
  static const int kScaleFactorFieldNumber = 12;
  float scale_factor() const;
  void set_scale_factor(float value);

  // float offset = 13;
  void clear_offset();
  static const int kOffsetFieldNumber = 13;
  float offset() const;
  void set_offset(float value);

  // @@protoc_insertion_point(class_scope:bevfusion.CameraConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > intrinsics_;
  mutable int _intrinsics_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > camera2lidar_;
  mutable int _camera2lidar_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > lidar2image_;
  mutable int _lidar2image_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > img_aug_matrix_;
  mutable int _img_aug_matrix_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > mean_;
  mutable int _mean_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > std_;
  mutable int _std_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr interpolation_;
  ::google::protobuf::uint32 image_width_;
  ::google::protobuf::uint32 image_height_;
  ::google::protobuf::uint32 output_width_;
  ::google::protobuf::uint32 output_height_;
  float resize_lim_;
  float scale_factor_;
  float offset_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_CameraConfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CameraConfig

// repeated float intrinsics = 1;
inline int CameraConfig::intrinsics_size() const {
  return intrinsics_.size();
}
inline void CameraConfig::clear_intrinsics() {
  intrinsics_.Clear();
}
inline float CameraConfig::intrinsics(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.intrinsics)
  return intrinsics_.Get(index);
}
inline void CameraConfig::set_intrinsics(int index, float value) {
  intrinsics_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.intrinsics)
}
inline void CameraConfig::add_intrinsics(float value) {
  intrinsics_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.CameraConfig.intrinsics)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraConfig::intrinsics() const {
  // @@protoc_insertion_point(field_list:bevfusion.CameraConfig.intrinsics)
  return intrinsics_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraConfig::mutable_intrinsics() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.CameraConfig.intrinsics)
  return &intrinsics_;
}

// repeated float camera2lidar = 2;
inline int CameraConfig::camera2lidar_size() const {
  return camera2lidar_.size();
}
inline void CameraConfig::clear_camera2lidar() {
  camera2lidar_.Clear();
}
inline float CameraConfig::camera2lidar(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.camera2lidar)
  return camera2lidar_.Get(index);
}
inline void CameraConfig::set_camera2lidar(int index, float value) {
  camera2lidar_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.camera2lidar)
}
inline void CameraConfig::add_camera2lidar(float value) {
  camera2lidar_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.CameraConfig.camera2lidar)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraConfig::camera2lidar() const {
  // @@protoc_insertion_point(field_list:bevfusion.CameraConfig.camera2lidar)
  return camera2lidar_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraConfig::mutable_camera2lidar() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.CameraConfig.camera2lidar)
  return &camera2lidar_;
}

// repeated float lidar2image = 3;
inline int CameraConfig::lidar2image_size() const {
  return lidar2image_.size();
}
inline void CameraConfig::clear_lidar2image() {
  lidar2image_.Clear();
}
inline float CameraConfig::lidar2image(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.lidar2image)
  return lidar2image_.Get(index);
}
inline void CameraConfig::set_lidar2image(int index, float value) {
  lidar2image_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.lidar2image)
}
inline void CameraConfig::add_lidar2image(float value) {
  lidar2image_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.CameraConfig.lidar2image)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraConfig::lidar2image() const {
  // @@protoc_insertion_point(field_list:bevfusion.CameraConfig.lidar2image)
  return lidar2image_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraConfig::mutable_lidar2image() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.CameraConfig.lidar2image)
  return &lidar2image_;
}

// repeated float img_aug_matrix = 4;
inline int CameraConfig::img_aug_matrix_size() const {
  return img_aug_matrix_.size();
}
inline void CameraConfig::clear_img_aug_matrix() {
  img_aug_matrix_.Clear();
}
inline float CameraConfig::img_aug_matrix(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.img_aug_matrix)
  return img_aug_matrix_.Get(index);
}
inline void CameraConfig::set_img_aug_matrix(int index, float value) {
  img_aug_matrix_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.img_aug_matrix)
}
inline void CameraConfig::add_img_aug_matrix(float value) {
  img_aug_matrix_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.CameraConfig.img_aug_matrix)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraConfig::img_aug_matrix() const {
  // @@protoc_insertion_point(field_list:bevfusion.CameraConfig.img_aug_matrix)
  return img_aug_matrix_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraConfig::mutable_img_aug_matrix() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.CameraConfig.img_aug_matrix)
  return &img_aug_matrix_;
}

// uint32 image_width = 5;
inline void CameraConfig::clear_image_width() {
  image_width_ = 0u;
}
inline ::google::protobuf::uint32 CameraConfig::image_width() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.image_width)
  return image_width_;
}
inline void CameraConfig::set_image_width(::google::protobuf::uint32 value) {
  
  image_width_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.image_width)
}

// uint32 image_height = 6;
inline void CameraConfig::clear_image_height() {
  image_height_ = 0u;
}
inline ::google::protobuf::uint32 CameraConfig::image_height() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.image_height)
  return image_height_;
}
inline void CameraConfig::set_image_height(::google::protobuf::uint32 value) {
  
  image_height_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.image_height)
}

// uint32 output_width = 7;
inline void CameraConfig::clear_output_width() {
  output_width_ = 0u;
}
inline ::google::protobuf::uint32 CameraConfig::output_width() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.output_width)
  return output_width_;
}
inline void CameraConfig::set_output_width(::google::protobuf::uint32 value) {
  
  output_width_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.output_width)
}

// uint32 output_height = 8;
inline void CameraConfig::clear_output_height() {
  output_height_ = 0u;
}
inline ::google::protobuf::uint32 CameraConfig::output_height() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.output_height)
  return output_height_;
}
inline void CameraConfig::set_output_height(::google::protobuf::uint32 value) {
  
  output_height_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.output_height)
}

// float resize_lim = 9;
inline void CameraConfig::clear_resize_lim() {
  resize_lim_ = 0;
}
inline float CameraConfig::resize_lim() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.resize_lim)
  return resize_lim_;
}
inline void CameraConfig::set_resize_lim(float value) {
  
  resize_lim_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.resize_lim)
}

// repeated float mean = 10;
inline int CameraConfig::mean_size() const {
  return mean_.size();
}
inline void CameraConfig::clear_mean() {
  mean_.Clear();
}
inline float CameraConfig::mean(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.mean)
  return mean_.Get(index);
}
inline void CameraConfig::set_mean(int index, float value) {
  mean_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.mean)
}
inline void CameraConfig::add_mean(float value) {
  mean_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.CameraConfig.mean)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraConfig::mean() const {
  // @@protoc_insertion_point(field_list:bevfusion.CameraConfig.mean)
  return mean_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraConfig::mutable_mean() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.CameraConfig.mean)
  return &mean_;
}

// repeated float std = 11;
inline int CameraConfig::std_size() const {
  return std_.size();
}
inline void CameraConfig::clear_std() {
  std_.Clear();
}
inline float CameraConfig::std(int index) const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.std)
  return std_.Get(index);
}
inline void CameraConfig::set_std(int index, float value) {
  std_.Set(index, value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.std)
}
inline void CameraConfig::add_std(float value) {
  std_.Add(value);
  // @@protoc_insertion_point(field_add:bevfusion.CameraConfig.std)
}
inline const ::google::protobuf::RepeatedField< float >&
CameraConfig::std() const {
  // @@protoc_insertion_point(field_list:bevfusion.CameraConfig.std)
  return std_;
}
inline ::google::protobuf::RepeatedField< float >*
CameraConfig::mutable_std() {
  // @@protoc_insertion_point(field_mutable_list:bevfusion.CameraConfig.std)
  return &std_;
}

// float scale_factor = 12;
inline void CameraConfig::clear_scale_factor() {
  scale_factor_ = 0;
}
inline float CameraConfig::scale_factor() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.scale_factor)
  return scale_factor_;
}
inline void CameraConfig::set_scale_factor(float value) {
  
  scale_factor_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.scale_factor)
}

// float offset = 13;
inline void CameraConfig::clear_offset() {
  offset_ = 0;
}
inline float CameraConfig::offset() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.offset)
  return offset_;
}
inline void CameraConfig::set_offset(float value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.offset)
}

// string interpolation = 14;
inline void CameraConfig::clear_interpolation() {
  interpolation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CameraConfig::interpolation() const {
  // @@protoc_insertion_point(field_get:bevfusion.CameraConfig.interpolation)
  return interpolation_.GetNoArena();
}
inline void CameraConfig::set_interpolation(const ::std::string& value) {
  
  interpolation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bevfusion.CameraConfig.interpolation)
}
#if LANG_CXX11
inline void CameraConfig::set_interpolation(::std::string&& value) {
  
  interpolation_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bevfusion.CameraConfig.interpolation)
}
#endif
inline void CameraConfig::set_interpolation(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  interpolation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bevfusion.CameraConfig.interpolation)
}
inline void CameraConfig::set_interpolation(const char* value, size_t size) {
  
  interpolation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bevfusion.CameraConfig.interpolation)
}
inline ::std::string* CameraConfig::mutable_interpolation() {
  
  // @@protoc_insertion_point(field_mutable:bevfusion.CameraConfig.interpolation)
  return interpolation_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CameraConfig::release_interpolation() {
  // @@protoc_insertion_point(field_release:bevfusion.CameraConfig.interpolation)
  
  return interpolation_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CameraConfig::set_allocated_interpolation(::std::string* interpolation) {
  if (interpolation != NULL) {
    
  } else {
    
  }
  interpolation_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), interpolation);
  // @@protoc_insertion_point(field_set_allocated:bevfusion.CameraConfig.interpolation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bevfusion

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_CameraConfig_2eproto
