// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CAlgResult.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "CAlgResult.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




CObjectResult::CObjectResult()
{
}

CObjectResult::~CObjectResult()
{
}

CObjectResult::CObjectResult(
        const CObjectResult& x)
{
    m_strClass = x.m_strClass;
    m_ucSource = x.m_ucSource;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
    m_l = x.m_l;
    m_h = x.m_h;
    m_yaw = x.m_yaw;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vz = x.m_vz;
    m_confidence = x.m_confidence;
    m_fusioned_confidence = x.m_fusioned_confidence;
    m_label = x.m_label;
    m_trackid = x.m_trackid;
}

CObjectResult::CObjectResult(
        CObjectResult&& x) noexcept
{
    m_strClass = std::move(x.m_strClass);
    m_ucSource = x.m_ucSource;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
    m_l = x.m_l;
    m_h = x.m_h;
    m_yaw = x.m_yaw;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vz = x.m_vz;
    m_confidence = x.m_confidence;
    m_fusioned_confidence = x.m_fusioned_confidence;
    m_label = x.m_label;
    m_trackid = x.m_trackid;
}

CObjectResult& CObjectResult::operator =(
        const CObjectResult& x)
{

    m_strClass = x.m_strClass;
    m_ucSource = x.m_ucSource;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
    m_l = x.m_l;
    m_h = x.m_h;
    m_yaw = x.m_yaw;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vz = x.m_vz;
    m_confidence = x.m_confidence;
    m_fusioned_confidence = x.m_fusioned_confidence;
    m_label = x.m_label;
    m_trackid = x.m_trackid;
    return *this;
}

CObjectResult& CObjectResult::operator =(
        CObjectResult&& x) noexcept
{

    m_strClass = std::move(x.m_strClass);
    m_ucSource = x.m_ucSource;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
    m_w = x.m_w;
    m_l = x.m_l;
    m_h = x.m_h;
    m_yaw = x.m_yaw;
    m_vx = x.m_vx;
    m_vy = x.m_vy;
    m_vz = x.m_vz;
    m_confidence = x.m_confidence;
    m_fusioned_confidence = x.m_fusioned_confidence;
    m_label = x.m_label;
    m_trackid = x.m_trackid;
    return *this;
}

bool CObjectResult::operator ==(
        const CObjectResult& x) const
{
    return (m_strClass == x.m_strClass &&
           m_ucSource == x.m_ucSource &&
           m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z &&
           m_w == x.m_w &&
           m_l == x.m_l &&
           m_h == x.m_h &&
           m_yaw == x.m_yaw &&
           m_vx == x.m_vx &&
           m_vy == x.m_vy &&
           m_vz == x.m_vz &&
           m_confidence == x.m_confidence &&
           m_fusioned_confidence == x.m_fusioned_confidence &&
           m_label == x.m_label &&
           m_trackid == x.m_trackid);
}

bool CObjectResult::operator !=(
        const CObjectResult& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member strClass
 * @param _strClass New value to be copied in member strClass
 */
void CObjectResult::strClass(
        const std::string& _strClass)
{
    m_strClass = _strClass;
}

/*!
 * @brief This function moves the value in member strClass
 * @param _strClass New value to be moved in member strClass
 */
void CObjectResult::strClass(
        std::string&& _strClass)
{
    m_strClass = std::move(_strClass);
}

/*!
 * @brief This function returns a constant reference to member strClass
 * @return Constant reference to member strClass
 */
const std::string& CObjectResult::strClass() const
{
    return m_strClass;
}

/*!
 * @brief This function returns a reference to member strClass
 * @return Reference to member strClass
 */
std::string& CObjectResult::strClass()
{
    return m_strClass;
}


/*!
 * @brief This function sets a value in member ucSource
 * @param _ucSource New value for member ucSource
 */
void CObjectResult::ucSource(
        uint8_t _ucSource)
{
    m_ucSource = _ucSource;
}

/*!
 * @brief This function returns the value of member ucSource
 * @return Value of member ucSource
 */
uint8_t CObjectResult::ucSource() const
{
    return m_ucSource;
}

/*!
 * @brief This function returns a reference to member ucSource
 * @return Reference to member ucSource
 */
uint8_t& CObjectResult::ucSource()
{
    return m_ucSource;
}


/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void CObjectResult::x(
        float _x)
{
    m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
float CObjectResult::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
float& CObjectResult::x()
{
    return m_x;
}


/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void CObjectResult::y(
        float _y)
{
    m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
float CObjectResult::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
float& CObjectResult::y()
{
    return m_y;
}


/*!
 * @brief This function sets a value in member z
 * @param _z New value for member z
 */
void CObjectResult::z(
        float _z)
{
    m_z = _z;
}

/*!
 * @brief This function returns the value of member z
 * @return Value of member z
 */
float CObjectResult::z() const
{
    return m_z;
}

/*!
 * @brief This function returns a reference to member z
 * @return Reference to member z
 */
float& CObjectResult::z()
{
    return m_z;
}


/*!
 * @brief This function sets a value in member w
 * @param _w New value for member w
 */
void CObjectResult::w(
        float _w)
{
    m_w = _w;
}

/*!
 * @brief This function returns the value of member w
 * @return Value of member w
 */
float CObjectResult::w() const
{
    return m_w;
}

/*!
 * @brief This function returns a reference to member w
 * @return Reference to member w
 */
float& CObjectResult::w()
{
    return m_w;
}


/*!
 * @brief This function sets a value in member l
 * @param _l New value for member l
 */
void CObjectResult::l(
        float _l)
{
    m_l = _l;
}

/*!
 * @brief This function returns the value of member l
 * @return Value of member l
 */
float CObjectResult::l() const
{
    return m_l;
}

/*!
 * @brief This function returns a reference to member l
 * @return Reference to member l
 */
float& CObjectResult::l()
{
    return m_l;
}


/*!
 * @brief This function sets a value in member h
 * @param _h New value for member h
 */
void CObjectResult::h(
        float _h)
{
    m_h = _h;
}

/*!
 * @brief This function returns the value of member h
 * @return Value of member h
 */
float CObjectResult::h() const
{
    return m_h;
}

/*!
 * @brief This function returns a reference to member h
 * @return Reference to member h
 */
float& CObjectResult::h()
{
    return m_h;
}


/*!
 * @brief This function sets a value in member yaw
 * @param _yaw New value for member yaw
 */
void CObjectResult::yaw(
        float _yaw)
{
    m_yaw = _yaw;
}

/*!
 * @brief This function returns the value of member yaw
 * @return Value of member yaw
 */
float CObjectResult::yaw() const
{
    return m_yaw;
}

/*!
 * @brief This function returns a reference to member yaw
 * @return Reference to member yaw
 */
float& CObjectResult::yaw()
{
    return m_yaw;
}


/*!
 * @brief This function sets a value in member vx
 * @param _vx New value for member vx
 */
void CObjectResult::vx(
        float _vx)
{
    m_vx = _vx;
}

/*!
 * @brief This function returns the value of member vx
 * @return Value of member vx
 */
float CObjectResult::vx() const
{
    return m_vx;
}

/*!
 * @brief This function returns a reference to member vx
 * @return Reference to member vx
 */
float& CObjectResult::vx()
{
    return m_vx;
}


/*!
 * @brief This function sets a value in member vy
 * @param _vy New value for member vy
 */
void CObjectResult::vy(
        float _vy)
{
    m_vy = _vy;
}

/*!
 * @brief This function returns the value of member vy
 * @return Value of member vy
 */
float CObjectResult::vy() const
{
    return m_vy;
}

/*!
 * @brief This function returns a reference to member vy
 * @return Reference to member vy
 */
float& CObjectResult::vy()
{
    return m_vy;
}


/*!
 * @brief This function sets a value in member vz
 * @param _vz New value for member vz
 */
void CObjectResult::vz(
        float _vz)
{
    m_vz = _vz;
}

/*!
 * @brief This function returns the value of member vz
 * @return Value of member vz
 */
float CObjectResult::vz() const
{
    return m_vz;
}

/*!
 * @brief This function returns a reference to member vz
 * @return Reference to member vz
 */
float& CObjectResult::vz()
{
    return m_vz;
}


/*!
 * @brief This function sets a value in member confidence
 * @param _confidence New value for member confidence
 */
void CObjectResult::confidence(
        float _confidence)
{
    m_confidence = _confidence;
}

/*!
 * @brief This function returns the value of member confidence
 * @return Value of member confidence
 */
float CObjectResult::confidence() const
{
    return m_confidence;
}

/*!
 * @brief This function returns a reference to member confidence
 * @return Reference to member confidence
 */
float& CObjectResult::confidence()
{
    return m_confidence;
}


/*!
 * @brief This function sets a value in member fusioned_confidence
 * @param _fusioned_confidence New value for member fusioned_confidence
 */
void CObjectResult::fusioned_confidence(
        float _fusioned_confidence)
{
    m_fusioned_confidence = _fusioned_confidence;
}

/*!
 * @brief This function returns the value of member fusioned_confidence
 * @return Value of member fusioned_confidence
 */
float CObjectResult::fusioned_confidence() const
{
    return m_fusioned_confidence;
}

/*!
 * @brief This function returns a reference to member fusioned_confidence
 * @return Reference to member fusioned_confidence
 */
float& CObjectResult::fusioned_confidence()
{
    return m_fusioned_confidence;
}


/*!
 * @brief This function sets a value in member label
 * @param _label New value for member label
 */
void CObjectResult::label(
        uint8_t _label)
{
    m_label = _label;
}

/*!
 * @brief This function returns the value of member label
 * @return Value of member label
 */
uint8_t CObjectResult::label() const
{
    return m_label;
}

/*!
 * @brief This function returns a reference to member label
 * @return Reference to member label
 */
uint8_t& CObjectResult::label()
{
    return m_label;
}


/*!
 * @brief This function sets a value in member trackid
 * @param _trackid New value for member trackid
 */
void CObjectResult::trackid(
        int32_t _trackid)
{
    m_trackid = _trackid;
}

/*!
 * @brief This function returns the value of member trackid
 * @return Value of member trackid
 */
int32_t CObjectResult::trackid() const
{
    return m_trackid;
}

/*!
 * @brief This function returns a reference to member trackid
 * @return Reference to member trackid
 */
int32_t& CObjectResult::trackid()
{
    return m_trackid;
}






CFrameResult::CFrameResult()
    : CDataBase()

{
}

CFrameResult::~CFrameResult()
{
}

CFrameResult::CFrameResult(
        const CFrameResult& x)
    : CDataBase(x)

{
    m_vecObjectResult = x.m_vecObjectResult;
}

CFrameResult::CFrameResult(
        CFrameResult&& x) noexcept
    : CDataBase(std::move(x))

{
    m_vecObjectResult = std::move(x.m_vecObjectResult);
}

CFrameResult& CFrameResult::operator =(
        const CFrameResult& x)
{
    CDataBase::operator =(x);

    m_vecObjectResult = x.m_vecObjectResult;
    return *this;
}

CFrameResult& CFrameResult::operator =(
        CFrameResult&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_vecObjectResult = std::move(x.m_vecObjectResult);
    return *this;
}

bool CFrameResult::operator ==(
        const CFrameResult& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_vecObjectResult == x.m_vecObjectResult);
}

bool CFrameResult::operator !=(
        const CFrameResult& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member vecObjectResult
 * @param _vecObjectResult New value to be copied in member vecObjectResult
 */
void CFrameResult::vecObjectResult(
        const std::vector<CObjectResult>& _vecObjectResult)
{
    m_vecObjectResult = _vecObjectResult;
}

/*!
 * @brief This function moves the value in member vecObjectResult
 * @param _vecObjectResult New value to be moved in member vecObjectResult
 */
void CFrameResult::vecObjectResult(
        std::vector<CObjectResult>&& _vecObjectResult)
{
    m_vecObjectResult = std::move(_vecObjectResult);
}

/*!
 * @brief This function returns a constant reference to member vecObjectResult
 * @return Constant reference to member vecObjectResult
 */
const std::vector<CObjectResult>& CFrameResult::vecObjectResult() const
{
    return m_vecObjectResult;
}

/*!
 * @brief This function returns a reference to member vecObjectResult
 * @return Reference to member vecObjectResult
 */
std::vector<CObjectResult>& CFrameResult::vecObjectResult()
{
    return m_vecObjectResult;
}






CAlgResult::CAlgResult()
    : CDataBase()

{
}

CAlgResult::~CAlgResult()
{
}

CAlgResult::CAlgResult(
        const CAlgResult& x)
    : CDataBase(x)

{
    m_vecFrameResult = x.m_vecFrameResult;
}

CAlgResult::CAlgResult(
        CAlgResult&& x) noexcept
    : CDataBase(std::move(x))

{
    m_vecFrameResult = std::move(x.m_vecFrameResult);
}

CAlgResult& CAlgResult::operator =(
        const CAlgResult& x)
{
    CDataBase::operator =(x);

    m_vecFrameResult = x.m_vecFrameResult;
    return *this;
}

CAlgResult& CAlgResult::operator =(
        CAlgResult&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_vecFrameResult = std::move(x.m_vecFrameResult);
    return *this;
}

bool CAlgResult::operator ==(
        const CAlgResult& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_vecFrameResult == x.m_vecFrameResult);
}

bool CAlgResult::operator !=(
        const CAlgResult& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member vecFrameResult
 * @param _vecFrameResult New value to be copied in member vecFrameResult
 */
void CAlgResult::vecFrameResult(
        const std::vector<CFrameResult>& _vecFrameResult)
{
    m_vecFrameResult = _vecFrameResult;
}

/*!
 * @brief This function moves the value in member vecFrameResult
 * @param _vecFrameResult New value to be moved in member vecFrameResult
 */
void CAlgResult::vecFrameResult(
        std::vector<CFrameResult>&& _vecFrameResult)
{
    m_vecFrameResult = std::move(_vecFrameResult);
}

/*!
 * @brief This function returns a constant reference to member vecFrameResult
 * @return Constant reference to member vecFrameResult
 */
const std::vector<CFrameResult>& CAlgResult::vecFrameResult() const
{
    return m_vecFrameResult;
}

/*!
 * @brief This function returns a reference to member vecFrameResult
 * @return Reference to member vecFrameResult
 */
std::vector<CFrameResult>& CAlgResult::vecFrameResult()
{
    return m_vecFrameResult;
}


// Include auxiliary functions like for serializing/deserializing.
#include "CAlgResultCdrAux.ipp"

