// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CAlgResult.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_CALGRESULT_H_
#define _FAST_DDS_GENERATED_CALGRESULT_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "CDataBase.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CALGRESULT_SOURCE)
#define CALGRESULT_DllAPI __declspec( dllexport )
#else
#define CALGRESULT_DllAPI __declspec( dllimport )
#endif // CALGRESULT_SOURCE
#else
#define CALGRESULT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CALGRESULT_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure CObjectResult defined by the user in the IDL file.
 * @ingroup CAlgResult
 */
class CObjectResult
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CObjectResult();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CObjectResult();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CObjectResult that will be copied.
     */
    eProsima_user_DllExport CObjectResult(
            const CObjectResult& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CObjectResult that will be copied.
     */
    eProsima_user_DllExport CObjectResult(
            CObjectResult&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CObjectResult that will be copied.
     */
    eProsima_user_DllExport CObjectResult& operator =(
            const CObjectResult& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CObjectResult that will be copied.
     */
    eProsima_user_DllExport CObjectResult& operator =(
            CObjectResult&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CObjectResult object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CObjectResult& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CObjectResult object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CObjectResult& x) const;

    /*!
     * @brief This function copies the value in member strClass
     * @param _strClass New value to be copied in member strClass
     */
    eProsima_user_DllExport void strClass(
            const std::string& _strClass);

    /*!
     * @brief This function moves the value in member strClass
     * @param _strClass New value to be moved in member strClass
     */
    eProsima_user_DllExport void strClass(
            std::string&& _strClass);

    /*!
     * @brief This function returns a constant reference to member strClass
     * @return Constant reference to member strClass
     */
    eProsima_user_DllExport const std::string& strClass() const;

    /*!
     * @brief This function returns a reference to member strClass
     * @return Reference to member strClass
     */
    eProsima_user_DllExport std::string& strClass();


    /*!
     * @brief This function sets a value in member ucSource
     * @param _ucSource New value for member ucSource
     */
    eProsima_user_DllExport void ucSource(
            uint8_t _ucSource);

    /*!
     * @brief This function returns the value of member ucSource
     * @return Value of member ucSource
     */
    eProsima_user_DllExport uint8_t ucSource() const;

    /*!
     * @brief This function returns a reference to member ucSource
     * @return Reference to member ucSource
     */
    eProsima_user_DllExport uint8_t& ucSource();


    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            float _x);

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport float x() const;

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport float& x();


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            float _y);

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport float y() const;

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport float& y();


    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    eProsima_user_DllExport void z(
            float _z);

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    eProsima_user_DllExport float z() const;

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport float& z();


    /*!
     * @brief This function sets a value in member w
     * @param _w New value for member w
     */
    eProsima_user_DllExport void w(
            float _w);

    /*!
     * @brief This function returns the value of member w
     * @return Value of member w
     */
    eProsima_user_DllExport float w() const;

    /*!
     * @brief This function returns a reference to member w
     * @return Reference to member w
     */
    eProsima_user_DllExport float& w();


    /*!
     * @brief This function sets a value in member l
     * @param _l New value for member l
     */
    eProsima_user_DllExport void l(
            float _l);

    /*!
     * @brief This function returns the value of member l
     * @return Value of member l
     */
    eProsima_user_DllExport float l() const;

    /*!
     * @brief This function returns a reference to member l
     * @return Reference to member l
     */
    eProsima_user_DllExport float& l();


    /*!
     * @brief This function sets a value in member h
     * @param _h New value for member h
     */
    eProsima_user_DllExport void h(
            float _h);

    /*!
     * @brief This function returns the value of member h
     * @return Value of member h
     */
    eProsima_user_DllExport float h() const;

    /*!
     * @brief This function returns a reference to member h
     * @return Reference to member h
     */
    eProsima_user_DllExport float& h();


    /*!
     * @brief This function sets a value in member yaw
     * @param _yaw New value for member yaw
     */
    eProsima_user_DllExport void yaw(
            float _yaw);

    /*!
     * @brief This function returns the value of member yaw
     * @return Value of member yaw
     */
    eProsima_user_DllExport float yaw() const;

    /*!
     * @brief This function returns a reference to member yaw
     * @return Reference to member yaw
     */
    eProsima_user_DllExport float& yaw();


    /*!
     * @brief This function sets a value in member vx
     * @param _vx New value for member vx
     */
    eProsima_user_DllExport void vx(
            float _vx);

    /*!
     * @brief This function returns the value of member vx
     * @return Value of member vx
     */
    eProsima_user_DllExport float vx() const;

    /*!
     * @brief This function returns a reference to member vx
     * @return Reference to member vx
     */
    eProsima_user_DllExport float& vx();


    /*!
     * @brief This function sets a value in member vy
     * @param _vy New value for member vy
     */
    eProsima_user_DllExport void vy(
            float _vy);

    /*!
     * @brief This function returns the value of member vy
     * @return Value of member vy
     */
    eProsima_user_DllExport float vy() const;

    /*!
     * @brief This function returns a reference to member vy
     * @return Reference to member vy
     */
    eProsima_user_DllExport float& vy();


    /*!
     * @brief This function sets a value in member vz
     * @param _vz New value for member vz
     */
    eProsima_user_DllExport void vz(
            float _vz);

    /*!
     * @brief This function returns the value of member vz
     * @return Value of member vz
     */
    eProsima_user_DllExport float vz() const;

    /*!
     * @brief This function returns a reference to member vz
     * @return Reference to member vz
     */
    eProsima_user_DllExport float& vz();


    /*!
     * @brief This function sets a value in member confidence
     * @param _confidence New value for member confidence
     */
    eProsima_user_DllExport void confidence(
            float _confidence);

    /*!
     * @brief This function returns the value of member confidence
     * @return Value of member confidence
     */
    eProsima_user_DllExport float confidence() const;

    /*!
     * @brief This function returns a reference to member confidence
     * @return Reference to member confidence
     */
    eProsima_user_DllExport float& confidence();


    /*!
     * @brief This function sets a value in member fusioned_confidence
     * @param _fusioned_confidence New value for member fusioned_confidence
     */
    eProsima_user_DllExport void fusioned_confidence(
            float _fusioned_confidence);

    /*!
     * @brief This function returns the value of member fusioned_confidence
     * @return Value of member fusioned_confidence
     */
    eProsima_user_DllExport float fusioned_confidence() const;

    /*!
     * @brief This function returns a reference to member fusioned_confidence
     * @return Reference to member fusioned_confidence
     */
    eProsima_user_DllExport float& fusioned_confidence();


    /*!
     * @brief This function sets a value in member label
     * @param _label New value for member label
     */
    eProsima_user_DllExport void label(
            uint8_t _label);

    /*!
     * @brief This function returns the value of member label
     * @return Value of member label
     */
    eProsima_user_DllExport uint8_t label() const;

    /*!
     * @brief This function returns a reference to member label
     * @return Reference to member label
     */
    eProsima_user_DllExport uint8_t& label();


    /*!
     * @brief This function sets a value in member trackid
     * @param _trackid New value for member trackid
     */
    eProsima_user_DllExport void trackid(
            int32_t _trackid);

    /*!
     * @brief This function returns the value of member trackid
     * @return Value of member trackid
     */
    eProsima_user_DllExport int32_t trackid() const;

    /*!
     * @brief This function returns a reference to member trackid
     * @return Reference to member trackid
     */
    eProsima_user_DllExport int32_t& trackid();

private:

    std::string m_strClass;
    uint8_t m_ucSource{0};
    float m_x{0.0};
    float m_y{0.0};
    float m_z{0.0};
    float m_w{0.0};
    float m_l{0.0};
    float m_h{0.0};
    float m_yaw{0.0};
    float m_vx{0.0};
    float m_vy{0.0};
    float m_vz{0.0};
    float m_confidence{0.0};
    float m_fusioned_confidence{0.0};
    uint8_t m_label{0};
    int32_t m_trackid{0};

};




/*!
 * @brief This class represents the structure CFrameResult defined by the user in the IDL file.
 * @ingroup CAlgResult
 */
class CFrameResult : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CFrameResult();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CFrameResult();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CFrameResult that will be copied.
     */
    eProsima_user_DllExport CFrameResult(
            const CFrameResult& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CFrameResult that will be copied.
     */
    eProsima_user_DllExport CFrameResult(
            CFrameResult&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CFrameResult that will be copied.
     */
    eProsima_user_DllExport CFrameResult& operator =(
            const CFrameResult& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CFrameResult that will be copied.
     */
    eProsima_user_DllExport CFrameResult& operator =(
            CFrameResult&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CFrameResult object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CFrameResult& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CFrameResult object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CFrameResult& x) const;

    /*!
     * @brief This function copies the value in member vecObjectResult
     * @param _vecObjectResult New value to be copied in member vecObjectResult
     */
    eProsima_user_DllExport void vecObjectResult(
            const std::vector<CObjectResult>& _vecObjectResult);

    /*!
     * @brief This function moves the value in member vecObjectResult
     * @param _vecObjectResult New value to be moved in member vecObjectResult
     */
    eProsima_user_DllExport void vecObjectResult(
            std::vector<CObjectResult>&& _vecObjectResult);

    /*!
     * @brief This function returns a constant reference to member vecObjectResult
     * @return Constant reference to member vecObjectResult
     */
    eProsima_user_DllExport const std::vector<CObjectResult>& vecObjectResult() const;

    /*!
     * @brief This function returns a reference to member vecObjectResult
     * @return Reference to member vecObjectResult
     */
    eProsima_user_DllExport std::vector<CObjectResult>& vecObjectResult();

private:

    std::vector<CObjectResult> m_vecObjectResult;

};




/*!
 * @brief This class represents the structure CAlgResult defined by the user in the IDL file.
 * @ingroup CAlgResult
 */
class CAlgResult : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CAlgResult();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CAlgResult();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CAlgResult that will be copied.
     */
    eProsima_user_DllExport CAlgResult(
            const CAlgResult& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CAlgResult that will be copied.
     */
    eProsima_user_DllExport CAlgResult(
            CAlgResult&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CAlgResult that will be copied.
     */
    eProsima_user_DllExport CAlgResult& operator =(
            const CAlgResult& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CAlgResult that will be copied.
     */
    eProsima_user_DllExport CAlgResult& operator =(
            CAlgResult&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CAlgResult object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CAlgResult& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CAlgResult object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CAlgResult& x) const;

    /*!
     * @brief This function copies the value in member vecFrameResult
     * @param _vecFrameResult New value to be copied in member vecFrameResult
     */
    eProsima_user_DllExport void vecFrameResult(
            const std::vector<CFrameResult>& _vecFrameResult);

    /*!
     * @brief This function moves the value in member vecFrameResult
     * @param _vecFrameResult New value to be moved in member vecFrameResult
     */
    eProsima_user_DllExport void vecFrameResult(
            std::vector<CFrameResult>&& _vecFrameResult);

    /*!
     * @brief This function returns a constant reference to member vecFrameResult
     * @return Constant reference to member vecFrameResult
     */
    eProsima_user_DllExport const std::vector<CFrameResult>& vecFrameResult() const;

    /*!
     * @brief This function returns a reference to member vecFrameResult
     * @return Reference to member vecFrameResult
     */
    eProsima_user_DllExport std::vector<CFrameResult>& vecFrameResult();

private:

    std::vector<CFrameResult> m_vecFrameResult;

};

#endif // _FAST_DDS_GENERATED_CALGRESULT_H_



