// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CTimeMatchSrcDataCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_CTIMEMATCHSRCDATACDRAUX_HPP_
#define _FAST_DDS_GENERATED_CTIMEMATCHSRCDATACDRAUX_HPP_

#include "CTimeMatchSrcData.h"

constexpr uint32_t CTestSrcData_max_cdr_typesize {4316UL};
constexpr uint32_t CTestSrcData_max_key_cdr_typesize {0UL};

constexpr uint32_t CLidar2EgoInfo_max_cdr_typesize {5108UL};
constexpr uint32_t CLidar2EgoInfo_max_key_cdr_typesize {0UL};


constexpr uint32_t CEgoPoseInfo_max_cdr_typesize {5108UL};
constexpr uint32_t CEgoPoseInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t CCalibrationData_max_cdr_typesize {3644UL};
constexpr uint32_t CCalibrationData_max_key_cdr_typesize {0UL};

constexpr uint32_t CTransformInfo_max_cdr_typesize {6464UL};
constexpr uint32_t CTransformInfo_max_key_cdr_typesize {0UL};

constexpr uint32_t CTimeMatchSrcData_max_cdr_typesize {365908UL};
constexpr uint32_t CTimeMatchSrcData_max_key_cdr_typesize {0UL};

constexpr uint32_t CLidarData_max_cdr_typesize {3640UL};
constexpr uint32_t CLidarData_max_key_cdr_typesize {0UL};

constexpr uint32_t CVideoSrcData_max_cdr_typesize {3348UL};
constexpr uint32_t CVideoSrcData_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CVideoSrcData& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CEgoPoseInfo& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CLidar2EgoInfo& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CTransformInfo& data);





eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CLidarData& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CCalibrationData& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CTestSrcData& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const CTimeMatchSrcData& data);


} // namespace fastcdr
} // namespace eprosima

#endif // _FAST_DDS_GENERATED_CTIMEMATCHSRCDATACDRAUX_HPP_

