// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CTimeMatchSrcData.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "CTimeMatchSrcData.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>






CVideoSrcData::CVideoSrcData()
    : CDataBase()

{
}

CVideoSrcData::~CVideoSrcData()
{
}

CVideoSrcData::CVideoSrcData(
        const CVideoSrcData& x)
    : CDataBase(x)

{
    m_ucCameraId = x.m_ucCameraId;
    m_usBmpLength = x.m_usBmpLength;
    m_usBmpWidth = x.m_usBmpWidth;
    m_unBmpBytes = x.m_unBmpBytes;
    m_vecImageBuf = x.m_vecImageBuf;
}

CVideoSrcData::CVideoSrcData(
        CVideoSrcData&& x) noexcept
    : CDataBase(std::move(x))

{
    m_ucCameraId = x.m_ucCameraId;
    m_usBmpLength = x.m_usBmpLength;
    m_usBmpWidth = x.m_usBmpWidth;
    m_unBmpBytes = x.m_unBmpBytes;
    m_vecImageBuf = std::move(x.m_vecImageBuf);
}

CVideoSrcData& CVideoSrcData::operator =(
        const CVideoSrcData& x)
{
    CDataBase::operator =(x);

    m_ucCameraId = x.m_ucCameraId;
    m_usBmpLength = x.m_usBmpLength;
    m_usBmpWidth = x.m_usBmpWidth;
    m_unBmpBytes = x.m_unBmpBytes;
    m_vecImageBuf = x.m_vecImageBuf;
    return *this;
}

CVideoSrcData& CVideoSrcData::operator =(
        CVideoSrcData&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_ucCameraId = x.m_ucCameraId;
    m_usBmpLength = x.m_usBmpLength;
    m_usBmpWidth = x.m_usBmpWidth;
    m_unBmpBytes = x.m_unBmpBytes;
    m_vecImageBuf = std::move(x.m_vecImageBuf);
    return *this;
}

bool CVideoSrcData::operator ==(
        const CVideoSrcData& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_ucCameraId == x.m_ucCameraId &&
           m_usBmpLength == x.m_usBmpLength &&
           m_usBmpWidth == x.m_usBmpWidth &&
           m_unBmpBytes == x.m_unBmpBytes &&
           m_vecImageBuf == x.m_vecImageBuf);
}

bool CVideoSrcData::operator !=(
        const CVideoSrcData& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member ucCameraId
 * @param _ucCameraId New value for member ucCameraId
 */
void CVideoSrcData::ucCameraId(
        uint8_t _ucCameraId)
{
    m_ucCameraId = _ucCameraId;
}

/*!
 * @brief This function returns the value of member ucCameraId
 * @return Value of member ucCameraId
 */
uint8_t CVideoSrcData::ucCameraId() const
{
    return m_ucCameraId;
}

/*!
 * @brief This function returns a reference to member ucCameraId
 * @return Reference to member ucCameraId
 */
uint8_t& CVideoSrcData::ucCameraId()
{
    return m_ucCameraId;
}


/*!
 * @brief This function sets a value in member usBmpLength
 * @param _usBmpLength New value for member usBmpLength
 */
void CVideoSrcData::usBmpLength(
        uint16_t _usBmpLength)
{
    m_usBmpLength = _usBmpLength;
}

/*!
 * @brief This function returns the value of member usBmpLength
 * @return Value of member usBmpLength
 */
uint16_t CVideoSrcData::usBmpLength() const
{
    return m_usBmpLength;
}

/*!
 * @brief This function returns a reference to member usBmpLength
 * @return Reference to member usBmpLength
 */
uint16_t& CVideoSrcData::usBmpLength()
{
    return m_usBmpLength;
}


/*!
 * @brief This function sets a value in member usBmpWidth
 * @param _usBmpWidth New value for member usBmpWidth
 */
void CVideoSrcData::usBmpWidth(
        uint16_t _usBmpWidth)
{
    m_usBmpWidth = _usBmpWidth;
}

/*!
 * @brief This function returns the value of member usBmpWidth
 * @return Value of member usBmpWidth
 */
uint16_t CVideoSrcData::usBmpWidth() const
{
    return m_usBmpWidth;
}

/*!
 * @brief This function returns a reference to member usBmpWidth
 * @return Reference to member usBmpWidth
 */
uint16_t& CVideoSrcData::usBmpWidth()
{
    return m_usBmpWidth;
}


/*!
 * @brief This function sets a value in member unBmpBytes
 * @param _unBmpBytes New value for member unBmpBytes
 */
void CVideoSrcData::unBmpBytes(
        uint32_t _unBmpBytes)
{
    m_unBmpBytes = _unBmpBytes;
}

/*!
 * @brief This function returns the value of member unBmpBytes
 * @return Value of member unBmpBytes
 */
uint32_t CVideoSrcData::unBmpBytes() const
{
    return m_unBmpBytes;
}

/*!
 * @brief This function returns a reference to member unBmpBytes
 * @return Reference to member unBmpBytes
 */
uint32_t& CVideoSrcData::unBmpBytes()
{
    return m_unBmpBytes;
}


/*!
 * @brief This function copies the value in member vecImageBuf
 * @param _vecImageBuf New value to be copied in member vecImageBuf
 */
void CVideoSrcData::vecImageBuf(
        const std::vector<uint8_t>& _vecImageBuf)
{
    m_vecImageBuf = _vecImageBuf;
}

/*!
 * @brief This function moves the value in member vecImageBuf
 * @param _vecImageBuf New value to be moved in member vecImageBuf
 */
void CVideoSrcData::vecImageBuf(
        std::vector<uint8_t>&& _vecImageBuf)
{
    m_vecImageBuf = std::move(_vecImageBuf);
}

/*!
 * @brief This function returns a constant reference to member vecImageBuf
 * @return Constant reference to member vecImageBuf
 */
const std::vector<uint8_t>& CVideoSrcData::vecImageBuf() const
{
    return m_vecImageBuf;
}

/*!
 * @brief This function returns a reference to member vecImageBuf
 * @return Reference to member vecImageBuf
 */
std::vector<uint8_t>& CVideoSrcData::vecImageBuf()
{
    return m_vecImageBuf;
}




CEgoPoseInfo::CEgoPoseInfo()
    : CDataBase()

{
}

CEgoPoseInfo::~CEgoPoseInfo()
{
}

CEgoPoseInfo::CEgoPoseInfo(
        const CEgoPoseInfo& x)
    : CDataBase(x)

{
    m_ego2global_translation = x.m_ego2global_translation;
    m_ego2global_rotation = x.m_ego2global_rotation;
    m_ego_pose_token = x.m_ego_pose_token;
}

CEgoPoseInfo::CEgoPoseInfo(
        CEgoPoseInfo&& x) noexcept
    : CDataBase(std::move(x))

{
    m_ego2global_translation = std::move(x.m_ego2global_translation);
    m_ego2global_rotation = std::move(x.m_ego2global_rotation);
    m_ego_pose_token = std::move(x.m_ego_pose_token);
}

CEgoPoseInfo& CEgoPoseInfo::operator =(
        const CEgoPoseInfo& x)
{
    CDataBase::operator =(x);

    m_ego2global_translation = x.m_ego2global_translation;
    m_ego2global_rotation = x.m_ego2global_rotation;
    m_ego_pose_token = x.m_ego_pose_token;
    return *this;
}

CEgoPoseInfo& CEgoPoseInfo::operator =(
        CEgoPoseInfo&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_ego2global_translation = std::move(x.m_ego2global_translation);
    m_ego2global_rotation = std::move(x.m_ego2global_rotation);
    m_ego_pose_token = std::move(x.m_ego_pose_token);
    return *this;
}

bool CEgoPoseInfo::operator ==(
        const CEgoPoseInfo& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_ego2global_translation == x.m_ego2global_translation &&
           m_ego2global_rotation == x.m_ego2global_rotation &&
           m_ego_pose_token == x.m_ego_pose_token);
}

bool CEgoPoseInfo::operator !=(
        const CEgoPoseInfo& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member ego2global_translation
 * @param _ego2global_translation New value to be copied in member ego2global_translation
 */
void CEgoPoseInfo::ego2global_translation(
        const std::vector<double>& _ego2global_translation)
{
    m_ego2global_translation = _ego2global_translation;
}

/*!
 * @brief This function moves the value in member ego2global_translation
 * @param _ego2global_translation New value to be moved in member ego2global_translation
 */
void CEgoPoseInfo::ego2global_translation(
        std::vector<double>&& _ego2global_translation)
{
    m_ego2global_translation = std::move(_ego2global_translation);
}

/*!
 * @brief This function returns a constant reference to member ego2global_translation
 * @return Constant reference to member ego2global_translation
 */
const std::vector<double>& CEgoPoseInfo::ego2global_translation() const
{
    return m_ego2global_translation;
}

/*!
 * @brief This function returns a reference to member ego2global_translation
 * @return Reference to member ego2global_translation
 */
std::vector<double>& CEgoPoseInfo::ego2global_translation()
{
    return m_ego2global_translation;
}


/*!
 * @brief This function copies the value in member ego2global_rotation
 * @param _ego2global_rotation New value to be copied in member ego2global_rotation
 */
void CEgoPoseInfo::ego2global_rotation(
        const std::vector<double>& _ego2global_rotation)
{
    m_ego2global_rotation = _ego2global_rotation;
}

/*!
 * @brief This function moves the value in member ego2global_rotation
 * @param _ego2global_rotation New value to be moved in member ego2global_rotation
 */
void CEgoPoseInfo::ego2global_rotation(
        std::vector<double>&& _ego2global_rotation)
{
    m_ego2global_rotation = std::move(_ego2global_rotation);
}

/*!
 * @brief This function returns a constant reference to member ego2global_rotation
 * @return Constant reference to member ego2global_rotation
 */
const std::vector<double>& CEgoPoseInfo::ego2global_rotation() const
{
    return m_ego2global_rotation;
}

/*!
 * @brief This function returns a reference to member ego2global_rotation
 * @return Reference to member ego2global_rotation
 */
std::vector<double>& CEgoPoseInfo::ego2global_rotation()
{
    return m_ego2global_rotation;
}


/*!
 * @brief This function copies the value in member ego_pose_token
 * @param _ego_pose_token New value to be copied in member ego_pose_token
 */
void CEgoPoseInfo::ego_pose_token(
        const std::string& _ego_pose_token)
{
    m_ego_pose_token = _ego_pose_token;
}

/*!
 * @brief This function moves the value in member ego_pose_token
 * @param _ego_pose_token New value to be moved in member ego_pose_token
 */
void CEgoPoseInfo::ego_pose_token(
        std::string&& _ego_pose_token)
{
    m_ego_pose_token = std::move(_ego_pose_token);
}

/*!
 * @brief This function returns a constant reference to member ego_pose_token
 * @return Constant reference to member ego_pose_token
 */
const std::string& CEgoPoseInfo::ego_pose_token() const
{
    return m_ego_pose_token;
}

/*!
 * @brief This function returns a reference to member ego_pose_token
 * @return Reference to member ego_pose_token
 */
std::string& CEgoPoseInfo::ego_pose_token()
{
    return m_ego_pose_token;
}




CLidar2EgoInfo::CLidar2EgoInfo()
    : CDataBase()

{
}

CLidar2EgoInfo::~CLidar2EgoInfo()
{
}

CLidar2EgoInfo::CLidar2EgoInfo(
        const CLidar2EgoInfo& x)
    : CDataBase(x)

{
    m_lidar2ego_translation = x.m_lidar2ego_translation;
    m_lidar2ego_rotation = x.m_lidar2ego_rotation;
    m_calibrated_sensor_token = x.m_calibrated_sensor_token;
}

CLidar2EgoInfo::CLidar2EgoInfo(
        CLidar2EgoInfo&& x) noexcept
    : CDataBase(std::move(x))

{
    m_lidar2ego_translation = std::move(x.m_lidar2ego_translation);
    m_lidar2ego_rotation = std::move(x.m_lidar2ego_rotation);
    m_calibrated_sensor_token = std::move(x.m_calibrated_sensor_token);
}

CLidar2EgoInfo& CLidar2EgoInfo::operator =(
        const CLidar2EgoInfo& x)
{
    CDataBase::operator =(x);

    m_lidar2ego_translation = x.m_lidar2ego_translation;
    m_lidar2ego_rotation = x.m_lidar2ego_rotation;
    m_calibrated_sensor_token = x.m_calibrated_sensor_token;
    return *this;
}

CLidar2EgoInfo& CLidar2EgoInfo::operator =(
        CLidar2EgoInfo&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_lidar2ego_translation = std::move(x.m_lidar2ego_translation);
    m_lidar2ego_rotation = std::move(x.m_lidar2ego_rotation);
    m_calibrated_sensor_token = std::move(x.m_calibrated_sensor_token);
    return *this;
}

bool CLidar2EgoInfo::operator ==(
        const CLidar2EgoInfo& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_lidar2ego_translation == x.m_lidar2ego_translation &&
           m_lidar2ego_rotation == x.m_lidar2ego_rotation &&
           m_calibrated_sensor_token == x.m_calibrated_sensor_token);
}

bool CLidar2EgoInfo::operator !=(
        const CLidar2EgoInfo& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member lidar2ego_translation
 * @param _lidar2ego_translation New value to be copied in member lidar2ego_translation
 */
void CLidar2EgoInfo::lidar2ego_translation(
        const std::vector<double>& _lidar2ego_translation)
{
    m_lidar2ego_translation = _lidar2ego_translation;
}

/*!
 * @brief This function moves the value in member lidar2ego_translation
 * @param _lidar2ego_translation New value to be moved in member lidar2ego_translation
 */
void CLidar2EgoInfo::lidar2ego_translation(
        std::vector<double>&& _lidar2ego_translation)
{
    m_lidar2ego_translation = std::move(_lidar2ego_translation);
}

/*!
 * @brief This function returns a constant reference to member lidar2ego_translation
 * @return Constant reference to member lidar2ego_translation
 */
const std::vector<double>& CLidar2EgoInfo::lidar2ego_translation() const
{
    return m_lidar2ego_translation;
}

/*!
 * @brief This function returns a reference to member lidar2ego_translation
 * @return Reference to member lidar2ego_translation
 */
std::vector<double>& CLidar2EgoInfo::lidar2ego_translation()
{
    return m_lidar2ego_translation;
}


/*!
 * @brief This function copies the value in member lidar2ego_rotation
 * @param _lidar2ego_rotation New value to be copied in member lidar2ego_rotation
 */
void CLidar2EgoInfo::lidar2ego_rotation(
        const std::vector<double>& _lidar2ego_rotation)
{
    m_lidar2ego_rotation = _lidar2ego_rotation;
}

/*!
 * @brief This function moves the value in member lidar2ego_rotation
 * @param _lidar2ego_rotation New value to be moved in member lidar2ego_rotation
 */
void CLidar2EgoInfo::lidar2ego_rotation(
        std::vector<double>&& _lidar2ego_rotation)
{
    m_lidar2ego_rotation = std::move(_lidar2ego_rotation);
}

/*!
 * @brief This function returns a constant reference to member lidar2ego_rotation
 * @return Constant reference to member lidar2ego_rotation
 */
const std::vector<double>& CLidar2EgoInfo::lidar2ego_rotation() const
{
    return m_lidar2ego_rotation;
}

/*!
 * @brief This function returns a reference to member lidar2ego_rotation
 * @return Reference to member lidar2ego_rotation
 */
std::vector<double>& CLidar2EgoInfo::lidar2ego_rotation()
{
    return m_lidar2ego_rotation;
}


/*!
 * @brief This function copies the value in member calibrated_sensor_token
 * @param _calibrated_sensor_token New value to be copied in member calibrated_sensor_token
 */
void CLidar2EgoInfo::calibrated_sensor_token(
        const std::string& _calibrated_sensor_token)
{
    m_calibrated_sensor_token = _calibrated_sensor_token;
}

/*!
 * @brief This function moves the value in member calibrated_sensor_token
 * @param _calibrated_sensor_token New value to be moved in member calibrated_sensor_token
 */
void CLidar2EgoInfo::calibrated_sensor_token(
        std::string&& _calibrated_sensor_token)
{
    m_calibrated_sensor_token = std::move(_calibrated_sensor_token);
}

/*!
 * @brief This function returns a constant reference to member calibrated_sensor_token
 * @return Constant reference to member calibrated_sensor_token
 */
const std::string& CLidar2EgoInfo::calibrated_sensor_token() const
{
    return m_calibrated_sensor_token;
}

/*!
 * @brief This function returns a reference to member calibrated_sensor_token
 * @return Reference to member calibrated_sensor_token
 */
std::string& CLidar2EgoInfo::calibrated_sensor_token()
{
    return m_calibrated_sensor_token;
}






CTransformInfo::CTransformInfo()
    : CDataBase()

{
}

CTransformInfo::~CTransformInfo()
{
}

CTransformInfo::CTransformInfo(
        const CTransformInfo& x)
    : CDataBase(x)

{
    m_lidar2ego_matrix = x.m_lidar2ego_matrix;
    m_ego2global_matrix = x.m_ego2global_matrix;
    m_lidar2global_matrix = x.m_lidar2global_matrix;
    m_global2lidar_matrix = x.m_global2lidar_matrix;
}

CTransformInfo::CTransformInfo(
        CTransformInfo&& x) noexcept
    : CDataBase(std::move(x))

{
    m_lidar2ego_matrix = std::move(x.m_lidar2ego_matrix);
    m_ego2global_matrix = std::move(x.m_ego2global_matrix);
    m_lidar2global_matrix = std::move(x.m_lidar2global_matrix);
    m_global2lidar_matrix = std::move(x.m_global2lidar_matrix);
}

CTransformInfo& CTransformInfo::operator =(
        const CTransformInfo& x)
{
    CDataBase::operator =(x);

    m_lidar2ego_matrix = x.m_lidar2ego_matrix;
    m_ego2global_matrix = x.m_ego2global_matrix;
    m_lidar2global_matrix = x.m_lidar2global_matrix;
    m_global2lidar_matrix = x.m_global2lidar_matrix;
    return *this;
}

CTransformInfo& CTransformInfo::operator =(
        CTransformInfo&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_lidar2ego_matrix = std::move(x.m_lidar2ego_matrix);
    m_ego2global_matrix = std::move(x.m_ego2global_matrix);
    m_lidar2global_matrix = std::move(x.m_lidar2global_matrix);
    m_global2lidar_matrix = std::move(x.m_global2lidar_matrix);
    return *this;
}

bool CTransformInfo::operator ==(
        const CTransformInfo& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_lidar2ego_matrix == x.m_lidar2ego_matrix &&
           m_ego2global_matrix == x.m_ego2global_matrix &&
           m_lidar2global_matrix == x.m_lidar2global_matrix &&
           m_global2lidar_matrix == x.m_global2lidar_matrix);
}

bool CTransformInfo::operator !=(
        const CTransformInfo& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member lidar2ego_matrix
 * @param _lidar2ego_matrix New value to be copied in member lidar2ego_matrix
 */
void CTransformInfo::lidar2ego_matrix(
        const std::vector<double>& _lidar2ego_matrix)
{
    m_lidar2ego_matrix = _lidar2ego_matrix;
}

/*!
 * @brief This function moves the value in member lidar2ego_matrix
 * @param _lidar2ego_matrix New value to be moved in member lidar2ego_matrix
 */
void CTransformInfo::lidar2ego_matrix(
        std::vector<double>&& _lidar2ego_matrix)
{
    m_lidar2ego_matrix = std::move(_lidar2ego_matrix);
}

/*!
 * @brief This function returns a constant reference to member lidar2ego_matrix
 * @return Constant reference to member lidar2ego_matrix
 */
const std::vector<double>& CTransformInfo::lidar2ego_matrix() const
{
    return m_lidar2ego_matrix;
}

/*!
 * @brief This function returns a reference to member lidar2ego_matrix
 * @return Reference to member lidar2ego_matrix
 */
std::vector<double>& CTransformInfo::lidar2ego_matrix()
{
    return m_lidar2ego_matrix;
}


/*!
 * @brief This function copies the value in member ego2global_matrix
 * @param _ego2global_matrix New value to be copied in member ego2global_matrix
 */
void CTransformInfo::ego2global_matrix(
        const std::vector<double>& _ego2global_matrix)
{
    m_ego2global_matrix = _ego2global_matrix;
}

/*!
 * @brief This function moves the value in member ego2global_matrix
 * @param _ego2global_matrix New value to be moved in member ego2global_matrix
 */
void CTransformInfo::ego2global_matrix(
        std::vector<double>&& _ego2global_matrix)
{
    m_ego2global_matrix = std::move(_ego2global_matrix);
}

/*!
 * @brief This function returns a constant reference to member ego2global_matrix
 * @return Constant reference to member ego2global_matrix
 */
const std::vector<double>& CTransformInfo::ego2global_matrix() const
{
    return m_ego2global_matrix;
}

/*!
 * @brief This function returns a reference to member ego2global_matrix
 * @return Reference to member ego2global_matrix
 */
std::vector<double>& CTransformInfo::ego2global_matrix()
{
    return m_ego2global_matrix;
}


/*!
 * @brief This function copies the value in member lidar2global_matrix
 * @param _lidar2global_matrix New value to be copied in member lidar2global_matrix
 */
void CTransformInfo::lidar2global_matrix(
        const std::vector<double>& _lidar2global_matrix)
{
    m_lidar2global_matrix = _lidar2global_matrix;
}

/*!
 * @brief This function moves the value in member lidar2global_matrix
 * @param _lidar2global_matrix New value to be moved in member lidar2global_matrix
 */
void CTransformInfo::lidar2global_matrix(
        std::vector<double>&& _lidar2global_matrix)
{
    m_lidar2global_matrix = std::move(_lidar2global_matrix);
}

/*!
 * @brief This function returns a constant reference to member lidar2global_matrix
 * @return Constant reference to member lidar2global_matrix
 */
const std::vector<double>& CTransformInfo::lidar2global_matrix() const
{
    return m_lidar2global_matrix;
}

/*!
 * @brief This function returns a reference to member lidar2global_matrix
 * @return Reference to member lidar2global_matrix
 */
std::vector<double>& CTransformInfo::lidar2global_matrix()
{
    return m_lidar2global_matrix;
}


/*!
 * @brief This function copies the value in member global2lidar_matrix
 * @param _global2lidar_matrix New value to be copied in member global2lidar_matrix
 */
void CTransformInfo::global2lidar_matrix(
        const std::vector<double>& _global2lidar_matrix)
{
    m_global2lidar_matrix = _global2lidar_matrix;
}

/*!
 * @brief This function moves the value in member global2lidar_matrix
 * @param _global2lidar_matrix New value to be moved in member global2lidar_matrix
 */
void CTransformInfo::global2lidar_matrix(
        std::vector<double>&& _global2lidar_matrix)
{
    m_global2lidar_matrix = std::move(_global2lidar_matrix);
}

/*!
 * @brief This function returns a constant reference to member global2lidar_matrix
 * @return Constant reference to member global2lidar_matrix
 */
const std::vector<double>& CTransformInfo::global2lidar_matrix() const
{
    return m_global2lidar_matrix;
}

/*!
 * @brief This function returns a reference to member global2lidar_matrix
 * @return Reference to member global2lidar_matrix
 */
std::vector<double>& CTransformInfo::global2lidar_matrix()
{
    return m_global2lidar_matrix;
}






CLidarData::CLidarData()
    : CDataBase()

{
}

CLidarData::~CLidarData()
{
}

CLidarData::CLidarData(
        const CLidarData& x)
    : CDataBase(x)

{
    m_num_points = x.m_num_points;
    m_points = x.m_points;
}

CLidarData::CLidarData(
        CLidarData&& x) noexcept
    : CDataBase(std::move(x))

{
    m_num_points = x.m_num_points;
    m_points = std::move(x.m_points);
}

CLidarData& CLidarData::operator =(
        const CLidarData& x)
{
    CDataBase::operator =(x);

    m_num_points = x.m_num_points;
    m_points = x.m_points;
    return *this;
}

CLidarData& CLidarData::operator =(
        CLidarData&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_num_points = x.m_num_points;
    m_points = std::move(x.m_points);
    return *this;
}

bool CLidarData::operator ==(
        const CLidarData& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_num_points == x.m_num_points &&
           m_points == x.m_points);
}

bool CLidarData::operator !=(
        const CLidarData& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member num_points
 * @param _num_points New value for member num_points
 */
void CLidarData::num_points(
        uint32_t _num_points)
{
    m_num_points = _num_points;
}

/*!
 * @brief This function returns the value of member num_points
 * @return Value of member num_points
 */
uint32_t CLidarData::num_points() const
{
    return m_num_points;
}

/*!
 * @brief This function returns a reference to member num_points
 * @return Reference to member num_points
 */
uint32_t& CLidarData::num_points()
{
    return m_num_points;
}


/*!
 * @brief This function copies the value in member points
 * @param _points New value to be copied in member points
 */
void CLidarData::points(
        const std::vector<float>& _points)
{
    m_points = _points;
}

/*!
 * @brief This function moves the value in member points
 * @param _points New value to be moved in member points
 */
void CLidarData::points(
        std::vector<float>&& _points)
{
    m_points = std::move(_points);
}

/*!
 * @brief This function returns a constant reference to member points
 * @return Constant reference to member points
 */
const std::vector<float>& CLidarData::points() const
{
    return m_points;
}

/*!
 * @brief This function returns a reference to member points
 * @return Reference to member points
 */
std::vector<float>& CLidarData::points()
{
    return m_points;
}




CCalibrationData::CCalibrationData()
    : CDataBase()

{
}

CCalibrationData::~CCalibrationData()
{
}

CCalibrationData::CCalibrationData(
        const CCalibrationData& x)
    : CDataBase(x)

{
    m_lidar2img_matrices = x.m_lidar2img_matrices;
    m_num_cameras = x.m_num_cameras;
    m_matrix_size = x.m_matrix_size;
}

CCalibrationData::CCalibrationData(
        CCalibrationData&& x) noexcept
    : CDataBase(std::move(x))

{
    m_lidar2img_matrices = std::move(x.m_lidar2img_matrices);
    m_num_cameras = x.m_num_cameras;
    m_matrix_size = x.m_matrix_size;
}

CCalibrationData& CCalibrationData::operator =(
        const CCalibrationData& x)
{
    CDataBase::operator =(x);

    m_lidar2img_matrices = x.m_lidar2img_matrices;
    m_num_cameras = x.m_num_cameras;
    m_matrix_size = x.m_matrix_size;
    return *this;
}

CCalibrationData& CCalibrationData::operator =(
        CCalibrationData&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_lidar2img_matrices = std::move(x.m_lidar2img_matrices);
    m_num_cameras = x.m_num_cameras;
    m_matrix_size = x.m_matrix_size;
    return *this;
}

bool CCalibrationData::operator ==(
        const CCalibrationData& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_lidar2img_matrices == x.m_lidar2img_matrices &&
           m_num_cameras == x.m_num_cameras &&
           m_matrix_size == x.m_matrix_size);
}

bool CCalibrationData::operator !=(
        const CCalibrationData& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member lidar2img_matrices
 * @param _lidar2img_matrices New value to be copied in member lidar2img_matrices
 */
void CCalibrationData::lidar2img_matrices(
        const std::vector<float>& _lidar2img_matrices)
{
    m_lidar2img_matrices = _lidar2img_matrices;
}

/*!
 * @brief This function moves the value in member lidar2img_matrices
 * @param _lidar2img_matrices New value to be moved in member lidar2img_matrices
 */
void CCalibrationData::lidar2img_matrices(
        std::vector<float>&& _lidar2img_matrices)
{
    m_lidar2img_matrices = std::move(_lidar2img_matrices);
}

/*!
 * @brief This function returns a constant reference to member lidar2img_matrices
 * @return Constant reference to member lidar2img_matrices
 */
const std::vector<float>& CCalibrationData::lidar2img_matrices() const
{
    return m_lidar2img_matrices;
}

/*!
 * @brief This function returns a reference to member lidar2img_matrices
 * @return Reference to member lidar2img_matrices
 */
std::vector<float>& CCalibrationData::lidar2img_matrices()
{
    return m_lidar2img_matrices;
}


/*!
 * @brief This function sets a value in member num_cameras
 * @param _num_cameras New value for member num_cameras
 */
void CCalibrationData::num_cameras(
        uint32_t _num_cameras)
{
    m_num_cameras = _num_cameras;
}

/*!
 * @brief This function returns the value of member num_cameras
 * @return Value of member num_cameras
 */
uint32_t CCalibrationData::num_cameras() const
{
    return m_num_cameras;
}

/*!
 * @brief This function returns a reference to member num_cameras
 * @return Reference to member num_cameras
 */
uint32_t& CCalibrationData::num_cameras()
{
    return m_num_cameras;
}


/*!
 * @brief This function sets a value in member matrix_size
 * @param _matrix_size New value for member matrix_size
 */
void CCalibrationData::matrix_size(
        uint32_t _matrix_size)
{
    m_matrix_size = _matrix_size;
}

/*!
 * @brief This function returns the value of member matrix_size
 * @return Value of member matrix_size
 */
uint32_t CCalibrationData::matrix_size() const
{
    return m_matrix_size;
}

/*!
 * @brief This function returns a reference to member matrix_size
 * @return Reference to member matrix_size
 */
uint32_t& CCalibrationData::matrix_size()
{
    return m_matrix_size;
}




CTestSrcData::CTestSrcData()
    : CDataBase()

{
}

CTestSrcData::~CTestSrcData()
{
}

CTestSrcData::CTestSrcData(
        const CTestSrcData& x)
    : CDataBase(x)

{
    m_expected_outputs = x.m_expected_outputs;
    m_preprocessed_imgs = x.m_preprocessed_imgs;
    m_img_channels = x.m_img_channels;
    m_img_height = x.m_img_height;
    m_img_width = x.m_img_width;
    m_test_data_path = x.m_test_data_path;
    m_test_data_type = x.m_test_data_type;
}

CTestSrcData::CTestSrcData(
        CTestSrcData&& x) noexcept
    : CDataBase(std::move(x))

{
    m_expected_outputs = std::move(x.m_expected_outputs);
    m_preprocessed_imgs = std::move(x.m_preprocessed_imgs);
    m_img_channels = x.m_img_channels;
    m_img_height = x.m_img_height;
    m_img_width = x.m_img_width;
    m_test_data_path = std::move(x.m_test_data_path);
    m_test_data_type = x.m_test_data_type;
}

CTestSrcData& CTestSrcData::operator =(
        const CTestSrcData& x)
{
    CDataBase::operator =(x);

    m_expected_outputs = x.m_expected_outputs;
    m_preprocessed_imgs = x.m_preprocessed_imgs;
    m_img_channels = x.m_img_channels;
    m_img_height = x.m_img_height;
    m_img_width = x.m_img_width;
    m_test_data_path = x.m_test_data_path;
    m_test_data_type = x.m_test_data_type;
    return *this;
}

CTestSrcData& CTestSrcData::operator =(
        CTestSrcData&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_expected_outputs = std::move(x.m_expected_outputs);
    m_preprocessed_imgs = std::move(x.m_preprocessed_imgs);
    m_img_channels = x.m_img_channels;
    m_img_height = x.m_img_height;
    m_img_width = x.m_img_width;
    m_test_data_path = std::move(x.m_test_data_path);
    m_test_data_type = x.m_test_data_type;
    return *this;
}

bool CTestSrcData::operator ==(
        const CTestSrcData& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_expected_outputs == x.m_expected_outputs &&
           m_preprocessed_imgs == x.m_preprocessed_imgs &&
           m_img_channels == x.m_img_channels &&
           m_img_height == x.m_img_height &&
           m_img_width == x.m_img_width &&
           m_test_data_path == x.m_test_data_path &&
           m_test_data_type == x.m_test_data_type);
}

bool CTestSrcData::operator !=(
        const CTestSrcData& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member expected_outputs
 * @param _expected_outputs New value to be copied in member expected_outputs
 */
void CTestSrcData::expected_outputs(
        const std::vector<float>& _expected_outputs)
{
    m_expected_outputs = _expected_outputs;
}

/*!
 * @brief This function moves the value in member expected_outputs
 * @param _expected_outputs New value to be moved in member expected_outputs
 */
void CTestSrcData::expected_outputs(
        std::vector<float>&& _expected_outputs)
{
    m_expected_outputs = std::move(_expected_outputs);
}

/*!
 * @brief This function returns a constant reference to member expected_outputs
 * @return Constant reference to member expected_outputs
 */
const std::vector<float>& CTestSrcData::expected_outputs() const
{
    return m_expected_outputs;
}

/*!
 * @brief This function returns a reference to member expected_outputs
 * @return Reference to member expected_outputs
 */
std::vector<float>& CTestSrcData::expected_outputs()
{
    return m_expected_outputs;
}


/*!
 * @brief This function copies the value in member preprocessed_imgs
 * @param _preprocessed_imgs New value to be copied in member preprocessed_imgs
 */
void CTestSrcData::preprocessed_imgs(
        const std::vector<float>& _preprocessed_imgs)
{
    m_preprocessed_imgs = _preprocessed_imgs;
}

/*!
 * @brief This function moves the value in member preprocessed_imgs
 * @param _preprocessed_imgs New value to be moved in member preprocessed_imgs
 */
void CTestSrcData::preprocessed_imgs(
        std::vector<float>&& _preprocessed_imgs)
{
    m_preprocessed_imgs = std::move(_preprocessed_imgs);
}

/*!
 * @brief This function returns a constant reference to member preprocessed_imgs
 * @return Constant reference to member preprocessed_imgs
 */
const std::vector<float>& CTestSrcData::preprocessed_imgs() const
{
    return m_preprocessed_imgs;
}

/*!
 * @brief This function returns a reference to member preprocessed_imgs
 * @return Reference to member preprocessed_imgs
 */
std::vector<float>& CTestSrcData::preprocessed_imgs()
{
    return m_preprocessed_imgs;
}


/*!
 * @brief This function sets a value in member img_channels
 * @param _img_channels New value for member img_channels
 */
void CTestSrcData::img_channels(
        uint32_t _img_channels)
{
    m_img_channels = _img_channels;
}

/*!
 * @brief This function returns the value of member img_channels
 * @return Value of member img_channels
 */
uint32_t CTestSrcData::img_channels() const
{
    return m_img_channels;
}

/*!
 * @brief This function returns a reference to member img_channels
 * @return Reference to member img_channels
 */
uint32_t& CTestSrcData::img_channels()
{
    return m_img_channels;
}


/*!
 * @brief This function sets a value in member img_height
 * @param _img_height New value for member img_height
 */
void CTestSrcData::img_height(
        uint32_t _img_height)
{
    m_img_height = _img_height;
}

/*!
 * @brief This function returns the value of member img_height
 * @return Value of member img_height
 */
uint32_t CTestSrcData::img_height() const
{
    return m_img_height;
}

/*!
 * @brief This function returns a reference to member img_height
 * @return Reference to member img_height
 */
uint32_t& CTestSrcData::img_height()
{
    return m_img_height;
}


/*!
 * @brief This function sets a value in member img_width
 * @param _img_width New value for member img_width
 */
void CTestSrcData::img_width(
        uint32_t _img_width)
{
    m_img_width = _img_width;
}

/*!
 * @brief This function returns the value of member img_width
 * @return Value of member img_width
 */
uint32_t CTestSrcData::img_width() const
{
    return m_img_width;
}

/*!
 * @brief This function returns a reference to member img_width
 * @return Reference to member img_width
 */
uint32_t& CTestSrcData::img_width()
{
    return m_img_width;
}


/*!
 * @brief This function copies the value in member test_data_path
 * @param _test_data_path New value to be copied in member test_data_path
 */
void CTestSrcData::test_data_path(
        const std::string& _test_data_path)
{
    m_test_data_path = _test_data_path;
}

/*!
 * @brief This function moves the value in member test_data_path
 * @param _test_data_path New value to be moved in member test_data_path
 */
void CTestSrcData::test_data_path(
        std::string&& _test_data_path)
{
    m_test_data_path = std::move(_test_data_path);
}

/*!
 * @brief This function returns a constant reference to member test_data_path
 * @return Constant reference to member test_data_path
 */
const std::string& CTestSrcData::test_data_path() const
{
    return m_test_data_path;
}

/*!
 * @brief This function returns a reference to member test_data_path
 * @return Reference to member test_data_path
 */
std::string& CTestSrcData::test_data_path()
{
    return m_test_data_path;
}


/*!
 * @brief This function sets a value in member test_data_type
 * @param _test_data_type New value for member test_data_type
 */
void CTestSrcData::test_data_type(
        uint32_t _test_data_type)
{
    m_test_data_type = _test_data_type;
}

/*!
 * @brief This function returns the value of member test_data_type
 * @return Value of member test_data_type
 */
uint32_t CTestSrcData::test_data_type() const
{
    return m_test_data_type;
}

/*!
 * @brief This function returns a reference to member test_data_type
 * @return Reference to member test_data_type
 */
uint32_t& CTestSrcData::test_data_type()
{
    return m_test_data_type;
}




CTimeMatchSrcData::CTimeMatchSrcData()
    : CDataBase()

{
}

CTimeMatchSrcData::~CTimeMatchSrcData()
{
}

CTimeMatchSrcData::CTimeMatchSrcData(
        const CTimeMatchSrcData& x)
    : CDataBase(x)

{
    m_vecVideoSrcData = x.m_vecVideoSrcData;
    m_ego_pose_info = x.m_ego_pose_info;
    m_lidar2ego_info = x.m_lidar2ego_info;
    m_transform_info = x.m_transform_info;
    m_lidar_data = x.m_lidar_data;
    m_calibration_data = x.m_calibration_data;
    m_test_data = x.m_test_data;
}

CTimeMatchSrcData::CTimeMatchSrcData(
        CTimeMatchSrcData&& x) noexcept
    : CDataBase(std::move(x))

{
    m_vecVideoSrcData = std::move(x.m_vecVideoSrcData);
    m_ego_pose_info = std::move(x.m_ego_pose_info);
    m_lidar2ego_info = std::move(x.m_lidar2ego_info);
    m_transform_info = std::move(x.m_transform_info);
    m_lidar_data = std::move(x.m_lidar_data);
    m_calibration_data = std::move(x.m_calibration_data);
    m_test_data = std::move(x.m_test_data);
}

CTimeMatchSrcData& CTimeMatchSrcData::operator =(
        const CTimeMatchSrcData& x)
{
    CDataBase::operator =(x);

    m_vecVideoSrcData = x.m_vecVideoSrcData;
    m_ego_pose_info = x.m_ego_pose_info;
    m_lidar2ego_info = x.m_lidar2ego_info;
    m_transform_info = x.m_transform_info;
    m_lidar_data = x.m_lidar_data;
    m_calibration_data = x.m_calibration_data;
    m_test_data = x.m_test_data;
    return *this;
}

CTimeMatchSrcData& CTimeMatchSrcData::operator =(
        CTimeMatchSrcData&& x) noexcept
{
    CDataBase::operator =(std::move(x));

    m_vecVideoSrcData = std::move(x.m_vecVideoSrcData);
    m_ego_pose_info = std::move(x.m_ego_pose_info);
    m_lidar2ego_info = std::move(x.m_lidar2ego_info);
    m_transform_info = std::move(x.m_transform_info);
    m_lidar_data = std::move(x.m_lidar_data);
    m_calibration_data = std::move(x.m_calibration_data);
    m_test_data = std::move(x.m_test_data);
    return *this;
}

bool CTimeMatchSrcData::operator ==(
        const CTimeMatchSrcData& x) const
{
    if (CDataBase::operator !=(x))
        {
            return false;
        }
    return (m_vecVideoSrcData == x.m_vecVideoSrcData &&
           m_ego_pose_info == x.m_ego_pose_info &&
           m_lidar2ego_info == x.m_lidar2ego_info &&
           m_transform_info == x.m_transform_info &&
           m_lidar_data == x.m_lidar_data &&
           m_calibration_data == x.m_calibration_data &&
           m_test_data == x.m_test_data);
}

bool CTimeMatchSrcData::operator !=(
        const CTimeMatchSrcData& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function copies the value in member vecVideoSrcData
 * @param _vecVideoSrcData New value to be copied in member vecVideoSrcData
 */
void CTimeMatchSrcData::vecVideoSrcData(
        const std::vector<CVideoSrcData>& _vecVideoSrcData)
{
    m_vecVideoSrcData = _vecVideoSrcData;
}

/*!
 * @brief This function moves the value in member vecVideoSrcData
 * @param _vecVideoSrcData New value to be moved in member vecVideoSrcData
 */
void CTimeMatchSrcData::vecVideoSrcData(
        std::vector<CVideoSrcData>&& _vecVideoSrcData)
{
    m_vecVideoSrcData = std::move(_vecVideoSrcData);
}

/*!
 * @brief This function returns a constant reference to member vecVideoSrcData
 * @return Constant reference to member vecVideoSrcData
 */
const std::vector<CVideoSrcData>& CTimeMatchSrcData::vecVideoSrcData() const
{
    return m_vecVideoSrcData;
}

/*!
 * @brief This function returns a reference to member vecVideoSrcData
 * @return Reference to member vecVideoSrcData
 */
std::vector<CVideoSrcData>& CTimeMatchSrcData::vecVideoSrcData()
{
    return m_vecVideoSrcData;
}


/*!
 * @brief This function copies the value in member ego_pose_info
 * @param _ego_pose_info New value to be copied in member ego_pose_info
 */
void CTimeMatchSrcData::ego_pose_info(
        const CEgoPoseInfo& _ego_pose_info)
{
    m_ego_pose_info = _ego_pose_info;
}

/*!
 * @brief This function moves the value in member ego_pose_info
 * @param _ego_pose_info New value to be moved in member ego_pose_info
 */
void CTimeMatchSrcData::ego_pose_info(
        CEgoPoseInfo&& _ego_pose_info)
{
    m_ego_pose_info = std::move(_ego_pose_info);
}

/*!
 * @brief This function returns a constant reference to member ego_pose_info
 * @return Constant reference to member ego_pose_info
 */
const CEgoPoseInfo& CTimeMatchSrcData::ego_pose_info() const
{
    return m_ego_pose_info;
}

/*!
 * @brief This function returns a reference to member ego_pose_info
 * @return Reference to member ego_pose_info
 */
CEgoPoseInfo& CTimeMatchSrcData::ego_pose_info()
{
    return m_ego_pose_info;
}


/*!
 * @brief This function copies the value in member lidar2ego_info
 * @param _lidar2ego_info New value to be copied in member lidar2ego_info
 */
void CTimeMatchSrcData::lidar2ego_info(
        const CLidar2EgoInfo& _lidar2ego_info)
{
    m_lidar2ego_info = _lidar2ego_info;
}

/*!
 * @brief This function moves the value in member lidar2ego_info
 * @param _lidar2ego_info New value to be moved in member lidar2ego_info
 */
void CTimeMatchSrcData::lidar2ego_info(
        CLidar2EgoInfo&& _lidar2ego_info)
{
    m_lidar2ego_info = std::move(_lidar2ego_info);
}

/*!
 * @brief This function returns a constant reference to member lidar2ego_info
 * @return Constant reference to member lidar2ego_info
 */
const CLidar2EgoInfo& CTimeMatchSrcData::lidar2ego_info() const
{
    return m_lidar2ego_info;
}

/*!
 * @brief This function returns a reference to member lidar2ego_info
 * @return Reference to member lidar2ego_info
 */
CLidar2EgoInfo& CTimeMatchSrcData::lidar2ego_info()
{
    return m_lidar2ego_info;
}


/*!
 * @brief This function copies the value in member transform_info
 * @param _transform_info New value to be copied in member transform_info
 */
void CTimeMatchSrcData::transform_info(
        const CTransformInfo& _transform_info)
{
    m_transform_info = _transform_info;
}

/*!
 * @brief This function moves the value in member transform_info
 * @param _transform_info New value to be moved in member transform_info
 */
void CTimeMatchSrcData::transform_info(
        CTransformInfo&& _transform_info)
{
    m_transform_info = std::move(_transform_info);
}

/*!
 * @brief This function returns a constant reference to member transform_info
 * @return Constant reference to member transform_info
 */
const CTransformInfo& CTimeMatchSrcData::transform_info() const
{
    return m_transform_info;
}

/*!
 * @brief This function returns a reference to member transform_info
 * @return Reference to member transform_info
 */
CTransformInfo& CTimeMatchSrcData::transform_info()
{
    return m_transform_info;
}


/*!
 * @brief This function copies the value in member lidar_data
 * @param _lidar_data New value to be copied in member lidar_data
 */
void CTimeMatchSrcData::lidar_data(
        const CLidarData& _lidar_data)
{
    m_lidar_data = _lidar_data;
}

/*!
 * @brief This function moves the value in member lidar_data
 * @param _lidar_data New value to be moved in member lidar_data
 */
void CTimeMatchSrcData::lidar_data(
        CLidarData&& _lidar_data)
{
    m_lidar_data = std::move(_lidar_data);
}

/*!
 * @brief This function returns a constant reference to member lidar_data
 * @return Constant reference to member lidar_data
 */
const CLidarData& CTimeMatchSrcData::lidar_data() const
{
    return m_lidar_data;
}

/*!
 * @brief This function returns a reference to member lidar_data
 * @return Reference to member lidar_data
 */
CLidarData& CTimeMatchSrcData::lidar_data()
{
    return m_lidar_data;
}


/*!
 * @brief This function copies the value in member calibration_data
 * @param _calibration_data New value to be copied in member calibration_data
 */
void CTimeMatchSrcData::calibration_data(
        const CCalibrationData& _calibration_data)
{
    m_calibration_data = _calibration_data;
}

/*!
 * @brief This function moves the value in member calibration_data
 * @param _calibration_data New value to be moved in member calibration_data
 */
void CTimeMatchSrcData::calibration_data(
        CCalibrationData&& _calibration_data)
{
    m_calibration_data = std::move(_calibration_data);
}

/*!
 * @brief This function returns a constant reference to member calibration_data
 * @return Constant reference to member calibration_data
 */
const CCalibrationData& CTimeMatchSrcData::calibration_data() const
{
    return m_calibration_data;
}

/*!
 * @brief This function returns a reference to member calibration_data
 * @return Reference to member calibration_data
 */
CCalibrationData& CTimeMatchSrcData::calibration_data()
{
    return m_calibration_data;
}


/*!
 * @brief This function copies the value in member test_data
 * @param _test_data New value to be copied in member test_data
 */
void CTimeMatchSrcData::test_data(
        const CTestSrcData& _test_data)
{
    m_test_data = _test_data;
}

/*!
 * @brief This function moves the value in member test_data
 * @param _test_data New value to be moved in member test_data
 */
void CTimeMatchSrcData::test_data(
        CTestSrcData&& _test_data)
{
    m_test_data = std::move(_test_data);
}

/*!
 * @brief This function returns a constant reference to member test_data
 * @return Constant reference to member test_data
 */
const CTestSrcData& CTimeMatchSrcData::test_data() const
{
    return m_test_data;
}

/*!
 * @brief This function returns a reference to member test_data
 * @return Reference to member test_data
 */
CTestSrcData& CTimeMatchSrcData::test_data()
{
    return m_test_data;
}


// Include auxiliary functions like for serializing/deserializing.
#include "CTimeMatchSrcDataCdrAux.ipp"

