// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CTimeMatchSrcData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_CTIMEMATCHSRCDATA_H_
#define _FAST_DDS_GENERATED_CTIMEMATCHSRCDATA_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>

#include "CDataBase.h"


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CTIMEMATCHSRCDATA_SOURCE)
#define CTIMEMATCHSRCDATA_DllAPI __declspec( dllexport )
#else
#define CTIMEMATCHSRCDATA_DllAPI __declspec( dllimport )
#endif // CTIMEMATCHSRCDATA_SOURCE
#else
#define CTIMEMATCHSRCDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CTIMEMATCHSRCDATA_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima







/*!
 * @brief This class represents the structure CVideoSrcData defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CVideoSrcData : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CVideoSrcData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CVideoSrcData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CVideoSrcData that will be copied.
     */
    eProsima_user_DllExport CVideoSrcData(
            const CVideoSrcData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CVideoSrcData that will be copied.
     */
    eProsima_user_DllExport CVideoSrcData(
            CVideoSrcData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CVideoSrcData that will be copied.
     */
    eProsima_user_DllExport CVideoSrcData& operator =(
            const CVideoSrcData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CVideoSrcData that will be copied.
     */
    eProsima_user_DllExport CVideoSrcData& operator =(
            CVideoSrcData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CVideoSrcData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CVideoSrcData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CVideoSrcData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CVideoSrcData& x) const;

    /*!
     * @brief This function sets a value in member ucCameraId
     * @param _ucCameraId New value for member ucCameraId
     */
    eProsima_user_DllExport void ucCameraId(
            uint8_t _ucCameraId);

    /*!
     * @brief This function returns the value of member ucCameraId
     * @return Value of member ucCameraId
     */
    eProsima_user_DllExport uint8_t ucCameraId() const;

    /*!
     * @brief This function returns a reference to member ucCameraId
     * @return Reference to member ucCameraId
     */
    eProsima_user_DllExport uint8_t& ucCameraId();


    /*!
     * @brief This function sets a value in member usBmpLength
     * @param _usBmpLength New value for member usBmpLength
     */
    eProsima_user_DllExport void usBmpLength(
            uint16_t _usBmpLength);

    /*!
     * @brief This function returns the value of member usBmpLength
     * @return Value of member usBmpLength
     */
    eProsima_user_DllExport uint16_t usBmpLength() const;

    /*!
     * @brief This function returns a reference to member usBmpLength
     * @return Reference to member usBmpLength
     */
    eProsima_user_DllExport uint16_t& usBmpLength();


    /*!
     * @brief This function sets a value in member usBmpWidth
     * @param _usBmpWidth New value for member usBmpWidth
     */
    eProsima_user_DllExport void usBmpWidth(
            uint16_t _usBmpWidth);

    /*!
     * @brief This function returns the value of member usBmpWidth
     * @return Value of member usBmpWidth
     */
    eProsima_user_DllExport uint16_t usBmpWidth() const;

    /*!
     * @brief This function returns a reference to member usBmpWidth
     * @return Reference to member usBmpWidth
     */
    eProsima_user_DllExport uint16_t& usBmpWidth();


    /*!
     * @brief This function sets a value in member unBmpBytes
     * @param _unBmpBytes New value for member unBmpBytes
     */
    eProsima_user_DllExport void unBmpBytes(
            uint32_t _unBmpBytes);

    /*!
     * @brief This function returns the value of member unBmpBytes
     * @return Value of member unBmpBytes
     */
    eProsima_user_DllExport uint32_t unBmpBytes() const;

    /*!
     * @brief This function returns a reference to member unBmpBytes
     * @return Reference to member unBmpBytes
     */
    eProsima_user_DllExport uint32_t& unBmpBytes();


    /*!
     * @brief This function copies the value in member vecImageBuf
     * @param _vecImageBuf New value to be copied in member vecImageBuf
     */
    eProsima_user_DllExport void vecImageBuf(
            const std::vector<uint8_t>& _vecImageBuf);

    /*!
     * @brief This function moves the value in member vecImageBuf
     * @param _vecImageBuf New value to be moved in member vecImageBuf
     */
    eProsima_user_DllExport void vecImageBuf(
            std::vector<uint8_t>&& _vecImageBuf);

    /*!
     * @brief This function returns a constant reference to member vecImageBuf
     * @return Constant reference to member vecImageBuf
     */
    eProsima_user_DllExport const std::vector<uint8_t>& vecImageBuf() const;

    /*!
     * @brief This function returns a reference to member vecImageBuf
     * @return Reference to member vecImageBuf
     */
    eProsima_user_DllExport std::vector<uint8_t>& vecImageBuf();

private:

    uint8_t m_ucCameraId{0};
    uint16_t m_usBmpLength{0};
    uint16_t m_usBmpWidth{0};
    uint32_t m_unBmpBytes{0};
    std::vector<uint8_t> m_vecImageBuf;

};


/*!
 * @brief This class represents the structure CEgoPoseInfo defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CEgoPoseInfo : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CEgoPoseInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CEgoPoseInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CEgoPoseInfo that will be copied.
     */
    eProsima_user_DllExport CEgoPoseInfo(
            const CEgoPoseInfo& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CEgoPoseInfo that will be copied.
     */
    eProsima_user_DllExport CEgoPoseInfo(
            CEgoPoseInfo&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CEgoPoseInfo that will be copied.
     */
    eProsima_user_DllExport CEgoPoseInfo& operator =(
            const CEgoPoseInfo& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CEgoPoseInfo that will be copied.
     */
    eProsima_user_DllExport CEgoPoseInfo& operator =(
            CEgoPoseInfo&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CEgoPoseInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CEgoPoseInfo& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CEgoPoseInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CEgoPoseInfo& x) const;

    /*!
     * @brief This function copies the value in member ego2global_translation
     * @param _ego2global_translation New value to be copied in member ego2global_translation
     */
    eProsima_user_DllExport void ego2global_translation(
            const std::vector<double>& _ego2global_translation);

    /*!
     * @brief This function moves the value in member ego2global_translation
     * @param _ego2global_translation New value to be moved in member ego2global_translation
     */
    eProsima_user_DllExport void ego2global_translation(
            std::vector<double>&& _ego2global_translation);

    /*!
     * @brief This function returns a constant reference to member ego2global_translation
     * @return Constant reference to member ego2global_translation
     */
    eProsima_user_DllExport const std::vector<double>& ego2global_translation() const;

    /*!
     * @brief This function returns a reference to member ego2global_translation
     * @return Reference to member ego2global_translation
     */
    eProsima_user_DllExport std::vector<double>& ego2global_translation();


    /*!
     * @brief This function copies the value in member ego2global_rotation
     * @param _ego2global_rotation New value to be copied in member ego2global_rotation
     */
    eProsima_user_DllExport void ego2global_rotation(
            const std::vector<double>& _ego2global_rotation);

    /*!
     * @brief This function moves the value in member ego2global_rotation
     * @param _ego2global_rotation New value to be moved in member ego2global_rotation
     */
    eProsima_user_DllExport void ego2global_rotation(
            std::vector<double>&& _ego2global_rotation);

    /*!
     * @brief This function returns a constant reference to member ego2global_rotation
     * @return Constant reference to member ego2global_rotation
     */
    eProsima_user_DllExport const std::vector<double>& ego2global_rotation() const;

    /*!
     * @brief This function returns a reference to member ego2global_rotation
     * @return Reference to member ego2global_rotation
     */
    eProsima_user_DllExport std::vector<double>& ego2global_rotation();


    /*!
     * @brief This function copies the value in member ego_pose_token
     * @param _ego_pose_token New value to be copied in member ego_pose_token
     */
    eProsima_user_DllExport void ego_pose_token(
            const std::string& _ego_pose_token);

    /*!
     * @brief This function moves the value in member ego_pose_token
     * @param _ego_pose_token New value to be moved in member ego_pose_token
     */
    eProsima_user_DllExport void ego_pose_token(
            std::string&& _ego_pose_token);

    /*!
     * @brief This function returns a constant reference to member ego_pose_token
     * @return Constant reference to member ego_pose_token
     */
    eProsima_user_DllExport const std::string& ego_pose_token() const;

    /*!
     * @brief This function returns a reference to member ego_pose_token
     * @return Reference to member ego_pose_token
     */
    eProsima_user_DllExport std::string& ego_pose_token();

private:

    std::vector<double> m_ego2global_translation;
    std::vector<double> m_ego2global_rotation;
    std::string m_ego_pose_token;

};


/*!
 * @brief This class represents the structure CLidar2EgoInfo defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CLidar2EgoInfo : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CLidar2EgoInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CLidar2EgoInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CLidar2EgoInfo that will be copied.
     */
    eProsima_user_DllExport CLidar2EgoInfo(
            const CLidar2EgoInfo& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CLidar2EgoInfo that will be copied.
     */
    eProsima_user_DllExport CLidar2EgoInfo(
            CLidar2EgoInfo&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CLidar2EgoInfo that will be copied.
     */
    eProsima_user_DllExport CLidar2EgoInfo& operator =(
            const CLidar2EgoInfo& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CLidar2EgoInfo that will be copied.
     */
    eProsima_user_DllExport CLidar2EgoInfo& operator =(
            CLidar2EgoInfo&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CLidar2EgoInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CLidar2EgoInfo& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CLidar2EgoInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CLidar2EgoInfo& x) const;

    /*!
     * @brief This function copies the value in member lidar2ego_translation
     * @param _lidar2ego_translation New value to be copied in member lidar2ego_translation
     */
    eProsima_user_DllExport void lidar2ego_translation(
            const std::vector<double>& _lidar2ego_translation);

    /*!
     * @brief This function moves the value in member lidar2ego_translation
     * @param _lidar2ego_translation New value to be moved in member lidar2ego_translation
     */
    eProsima_user_DllExport void lidar2ego_translation(
            std::vector<double>&& _lidar2ego_translation);

    /*!
     * @brief This function returns a constant reference to member lidar2ego_translation
     * @return Constant reference to member lidar2ego_translation
     */
    eProsima_user_DllExport const std::vector<double>& lidar2ego_translation() const;

    /*!
     * @brief This function returns a reference to member lidar2ego_translation
     * @return Reference to member lidar2ego_translation
     */
    eProsima_user_DllExport std::vector<double>& lidar2ego_translation();


    /*!
     * @brief This function copies the value in member lidar2ego_rotation
     * @param _lidar2ego_rotation New value to be copied in member lidar2ego_rotation
     */
    eProsima_user_DllExport void lidar2ego_rotation(
            const std::vector<double>& _lidar2ego_rotation);

    /*!
     * @brief This function moves the value in member lidar2ego_rotation
     * @param _lidar2ego_rotation New value to be moved in member lidar2ego_rotation
     */
    eProsima_user_DllExport void lidar2ego_rotation(
            std::vector<double>&& _lidar2ego_rotation);

    /*!
     * @brief This function returns a constant reference to member lidar2ego_rotation
     * @return Constant reference to member lidar2ego_rotation
     */
    eProsima_user_DllExport const std::vector<double>& lidar2ego_rotation() const;

    /*!
     * @brief This function returns a reference to member lidar2ego_rotation
     * @return Reference to member lidar2ego_rotation
     */
    eProsima_user_DllExport std::vector<double>& lidar2ego_rotation();


    /*!
     * @brief This function copies the value in member calibrated_sensor_token
     * @param _calibrated_sensor_token New value to be copied in member calibrated_sensor_token
     */
    eProsima_user_DllExport void calibrated_sensor_token(
            const std::string& _calibrated_sensor_token);

    /*!
     * @brief This function moves the value in member calibrated_sensor_token
     * @param _calibrated_sensor_token New value to be moved in member calibrated_sensor_token
     */
    eProsima_user_DllExport void calibrated_sensor_token(
            std::string&& _calibrated_sensor_token);

    /*!
     * @brief This function returns a constant reference to member calibrated_sensor_token
     * @return Constant reference to member calibrated_sensor_token
     */
    eProsima_user_DllExport const std::string& calibrated_sensor_token() const;

    /*!
     * @brief This function returns a reference to member calibrated_sensor_token
     * @return Reference to member calibrated_sensor_token
     */
    eProsima_user_DllExport std::string& calibrated_sensor_token();

private:

    std::vector<double> m_lidar2ego_translation;
    std::vector<double> m_lidar2ego_rotation;
    std::string m_calibrated_sensor_token;

};




/*!
 * @brief This class represents the structure CTransformInfo defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CTransformInfo : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CTransformInfo();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CTransformInfo();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CTransformInfo that will be copied.
     */
    eProsima_user_DllExport CTransformInfo(
            const CTransformInfo& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CTransformInfo that will be copied.
     */
    eProsima_user_DllExport CTransformInfo(
            CTransformInfo&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CTransformInfo that will be copied.
     */
    eProsima_user_DllExport CTransformInfo& operator =(
            const CTransformInfo& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CTransformInfo that will be copied.
     */
    eProsima_user_DllExport CTransformInfo& operator =(
            CTransformInfo&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CTransformInfo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CTransformInfo& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CTransformInfo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CTransformInfo& x) const;

    /*!
     * @brief This function copies the value in member lidar2ego_matrix
     * @param _lidar2ego_matrix New value to be copied in member lidar2ego_matrix
     */
    eProsima_user_DllExport void lidar2ego_matrix(
            const std::vector<double>& _lidar2ego_matrix);

    /*!
     * @brief This function moves the value in member lidar2ego_matrix
     * @param _lidar2ego_matrix New value to be moved in member lidar2ego_matrix
     */
    eProsima_user_DllExport void lidar2ego_matrix(
            std::vector<double>&& _lidar2ego_matrix);

    /*!
     * @brief This function returns a constant reference to member lidar2ego_matrix
     * @return Constant reference to member lidar2ego_matrix
     */
    eProsima_user_DllExport const std::vector<double>& lidar2ego_matrix() const;

    /*!
     * @brief This function returns a reference to member lidar2ego_matrix
     * @return Reference to member lidar2ego_matrix
     */
    eProsima_user_DllExport std::vector<double>& lidar2ego_matrix();


    /*!
     * @brief This function copies the value in member ego2global_matrix
     * @param _ego2global_matrix New value to be copied in member ego2global_matrix
     */
    eProsima_user_DllExport void ego2global_matrix(
            const std::vector<double>& _ego2global_matrix);

    /*!
     * @brief This function moves the value in member ego2global_matrix
     * @param _ego2global_matrix New value to be moved in member ego2global_matrix
     */
    eProsima_user_DllExport void ego2global_matrix(
            std::vector<double>&& _ego2global_matrix);

    /*!
     * @brief This function returns a constant reference to member ego2global_matrix
     * @return Constant reference to member ego2global_matrix
     */
    eProsima_user_DllExport const std::vector<double>& ego2global_matrix() const;

    /*!
     * @brief This function returns a reference to member ego2global_matrix
     * @return Reference to member ego2global_matrix
     */
    eProsima_user_DllExport std::vector<double>& ego2global_matrix();


    /*!
     * @brief This function copies the value in member lidar2global_matrix
     * @param _lidar2global_matrix New value to be copied in member lidar2global_matrix
     */
    eProsima_user_DllExport void lidar2global_matrix(
            const std::vector<double>& _lidar2global_matrix);

    /*!
     * @brief This function moves the value in member lidar2global_matrix
     * @param _lidar2global_matrix New value to be moved in member lidar2global_matrix
     */
    eProsima_user_DllExport void lidar2global_matrix(
            std::vector<double>&& _lidar2global_matrix);

    /*!
     * @brief This function returns a constant reference to member lidar2global_matrix
     * @return Constant reference to member lidar2global_matrix
     */
    eProsima_user_DllExport const std::vector<double>& lidar2global_matrix() const;

    /*!
     * @brief This function returns a reference to member lidar2global_matrix
     * @return Reference to member lidar2global_matrix
     */
    eProsima_user_DllExport std::vector<double>& lidar2global_matrix();


    /*!
     * @brief This function copies the value in member global2lidar_matrix
     * @param _global2lidar_matrix New value to be copied in member global2lidar_matrix
     */
    eProsima_user_DllExport void global2lidar_matrix(
            const std::vector<double>& _global2lidar_matrix);

    /*!
     * @brief This function moves the value in member global2lidar_matrix
     * @param _global2lidar_matrix New value to be moved in member global2lidar_matrix
     */
    eProsima_user_DllExport void global2lidar_matrix(
            std::vector<double>&& _global2lidar_matrix);

    /*!
     * @brief This function returns a constant reference to member global2lidar_matrix
     * @return Constant reference to member global2lidar_matrix
     */
    eProsima_user_DllExport const std::vector<double>& global2lidar_matrix() const;

    /*!
     * @brief This function returns a reference to member global2lidar_matrix
     * @return Reference to member global2lidar_matrix
     */
    eProsima_user_DllExport std::vector<double>& global2lidar_matrix();

private:

    std::vector<double> m_lidar2ego_matrix;
    std::vector<double> m_ego2global_matrix;
    std::vector<double> m_lidar2global_matrix;
    std::vector<double> m_global2lidar_matrix;

};




/*!
 * @brief This class represents the structure CLidarData defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CLidarData : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CLidarData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CLidarData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CLidarData that will be copied.
     */
    eProsima_user_DllExport CLidarData(
            const CLidarData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CLidarData that will be copied.
     */
    eProsima_user_DllExport CLidarData(
            CLidarData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CLidarData that will be copied.
     */
    eProsima_user_DllExport CLidarData& operator =(
            const CLidarData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CLidarData that will be copied.
     */
    eProsima_user_DllExport CLidarData& operator =(
            CLidarData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CLidarData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CLidarData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CLidarData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CLidarData& x) const;

    /*!
     * @brief This function sets a value in member num_points
     * @param _num_points New value for member num_points
     */
    eProsima_user_DllExport void num_points(
            uint32_t _num_points);

    /*!
     * @brief This function returns the value of member num_points
     * @return Value of member num_points
     */
    eProsima_user_DllExport uint32_t num_points() const;

    /*!
     * @brief This function returns a reference to member num_points
     * @return Reference to member num_points
     */
    eProsima_user_DllExport uint32_t& num_points();


    /*!
     * @brief This function copies the value in member points
     * @param _points New value to be copied in member points
     */
    eProsima_user_DllExport void points(
            const std::vector<float>& _points);

    /*!
     * @brief This function moves the value in member points
     * @param _points New value to be moved in member points
     */
    eProsima_user_DllExport void points(
            std::vector<float>&& _points);

    /*!
     * @brief This function returns a constant reference to member points
     * @return Constant reference to member points
     */
    eProsima_user_DllExport const std::vector<float>& points() const;

    /*!
     * @brief This function returns a reference to member points
     * @return Reference to member points
     */
    eProsima_user_DllExport std::vector<float>& points();

private:

    uint32_t m_num_points{0};
    std::vector<float> m_points;

};


/*!
 * @brief This class represents the structure CCalibrationData defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CCalibrationData : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CCalibrationData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CCalibrationData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CCalibrationData that will be copied.
     */
    eProsima_user_DllExport CCalibrationData(
            const CCalibrationData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CCalibrationData that will be copied.
     */
    eProsima_user_DllExport CCalibrationData(
            CCalibrationData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CCalibrationData that will be copied.
     */
    eProsima_user_DllExport CCalibrationData& operator =(
            const CCalibrationData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CCalibrationData that will be copied.
     */
    eProsima_user_DllExport CCalibrationData& operator =(
            CCalibrationData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CCalibrationData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CCalibrationData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CCalibrationData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CCalibrationData& x) const;

    /*!
     * @brief This function copies the value in member lidar2img_matrices
     * @param _lidar2img_matrices New value to be copied in member lidar2img_matrices
     */
    eProsima_user_DllExport void lidar2img_matrices(
            const std::vector<float>& _lidar2img_matrices);

    /*!
     * @brief This function moves the value in member lidar2img_matrices
     * @param _lidar2img_matrices New value to be moved in member lidar2img_matrices
     */
    eProsima_user_DllExport void lidar2img_matrices(
            std::vector<float>&& _lidar2img_matrices);

    /*!
     * @brief This function returns a constant reference to member lidar2img_matrices
     * @return Constant reference to member lidar2img_matrices
     */
    eProsima_user_DllExport const std::vector<float>& lidar2img_matrices() const;

    /*!
     * @brief This function returns a reference to member lidar2img_matrices
     * @return Reference to member lidar2img_matrices
     */
    eProsima_user_DllExport std::vector<float>& lidar2img_matrices();


    /*!
     * @brief This function sets a value in member num_cameras
     * @param _num_cameras New value for member num_cameras
     */
    eProsima_user_DllExport void num_cameras(
            uint32_t _num_cameras);

    /*!
     * @brief This function returns the value of member num_cameras
     * @return Value of member num_cameras
     */
    eProsima_user_DllExport uint32_t num_cameras() const;

    /*!
     * @brief This function returns a reference to member num_cameras
     * @return Reference to member num_cameras
     */
    eProsima_user_DllExport uint32_t& num_cameras();


    /*!
     * @brief This function sets a value in member matrix_size
     * @param _matrix_size New value for member matrix_size
     */
    eProsima_user_DllExport void matrix_size(
            uint32_t _matrix_size);

    /*!
     * @brief This function returns the value of member matrix_size
     * @return Value of member matrix_size
     */
    eProsima_user_DllExport uint32_t matrix_size() const;

    /*!
     * @brief This function returns a reference to member matrix_size
     * @return Reference to member matrix_size
     */
    eProsima_user_DllExport uint32_t& matrix_size();

private:

    std::vector<float> m_lidar2img_matrices;
    uint32_t m_num_cameras{0};
    uint32_t m_matrix_size{0};

};


/*!
 * @brief This class represents the structure CTestSrcData defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CTestSrcData : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CTestSrcData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CTestSrcData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CTestSrcData that will be copied.
     */
    eProsima_user_DllExport CTestSrcData(
            const CTestSrcData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CTestSrcData that will be copied.
     */
    eProsima_user_DllExport CTestSrcData(
            CTestSrcData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CTestSrcData that will be copied.
     */
    eProsima_user_DllExport CTestSrcData& operator =(
            const CTestSrcData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CTestSrcData that will be copied.
     */
    eProsima_user_DllExport CTestSrcData& operator =(
            CTestSrcData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CTestSrcData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CTestSrcData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CTestSrcData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CTestSrcData& x) const;

    /*!
     * @brief This function copies the value in member expected_outputs
     * @param _expected_outputs New value to be copied in member expected_outputs
     */
    eProsima_user_DllExport void expected_outputs(
            const std::vector<float>& _expected_outputs);

    /*!
     * @brief This function moves the value in member expected_outputs
     * @param _expected_outputs New value to be moved in member expected_outputs
     */
    eProsima_user_DllExport void expected_outputs(
            std::vector<float>&& _expected_outputs);

    /*!
     * @brief This function returns a constant reference to member expected_outputs
     * @return Constant reference to member expected_outputs
     */
    eProsima_user_DllExport const std::vector<float>& expected_outputs() const;

    /*!
     * @brief This function returns a reference to member expected_outputs
     * @return Reference to member expected_outputs
     */
    eProsima_user_DllExport std::vector<float>& expected_outputs();


    /*!
     * @brief This function copies the value in member preprocessed_imgs
     * @param _preprocessed_imgs New value to be copied in member preprocessed_imgs
     */
    eProsima_user_DllExport void preprocessed_imgs(
            const std::vector<float>& _preprocessed_imgs);

    /*!
     * @brief This function moves the value in member preprocessed_imgs
     * @param _preprocessed_imgs New value to be moved in member preprocessed_imgs
     */
    eProsima_user_DllExport void preprocessed_imgs(
            std::vector<float>&& _preprocessed_imgs);

    /*!
     * @brief This function returns a constant reference to member preprocessed_imgs
     * @return Constant reference to member preprocessed_imgs
     */
    eProsima_user_DllExport const std::vector<float>& preprocessed_imgs() const;

    /*!
     * @brief This function returns a reference to member preprocessed_imgs
     * @return Reference to member preprocessed_imgs
     */
    eProsima_user_DllExport std::vector<float>& preprocessed_imgs();


    /*!
     * @brief This function sets a value in member img_channels
     * @param _img_channels New value for member img_channels
     */
    eProsima_user_DllExport void img_channels(
            uint32_t _img_channels);

    /*!
     * @brief This function returns the value of member img_channels
     * @return Value of member img_channels
     */
    eProsima_user_DllExport uint32_t img_channels() const;

    /*!
     * @brief This function returns a reference to member img_channels
     * @return Reference to member img_channels
     */
    eProsima_user_DllExport uint32_t& img_channels();


    /*!
     * @brief This function sets a value in member img_height
     * @param _img_height New value for member img_height
     */
    eProsima_user_DllExport void img_height(
            uint32_t _img_height);

    /*!
     * @brief This function returns the value of member img_height
     * @return Value of member img_height
     */
    eProsima_user_DllExport uint32_t img_height() const;

    /*!
     * @brief This function returns a reference to member img_height
     * @return Reference to member img_height
     */
    eProsima_user_DllExport uint32_t& img_height();


    /*!
     * @brief This function sets a value in member img_width
     * @param _img_width New value for member img_width
     */
    eProsima_user_DllExport void img_width(
            uint32_t _img_width);

    /*!
     * @brief This function returns the value of member img_width
     * @return Value of member img_width
     */
    eProsima_user_DllExport uint32_t img_width() const;

    /*!
     * @brief This function returns a reference to member img_width
     * @return Reference to member img_width
     */
    eProsima_user_DllExport uint32_t& img_width();


    /*!
     * @brief This function copies the value in member test_data_path
     * @param _test_data_path New value to be copied in member test_data_path
     */
    eProsima_user_DllExport void test_data_path(
            const std::string& _test_data_path);

    /*!
     * @brief This function moves the value in member test_data_path
     * @param _test_data_path New value to be moved in member test_data_path
     */
    eProsima_user_DllExport void test_data_path(
            std::string&& _test_data_path);

    /*!
     * @brief This function returns a constant reference to member test_data_path
     * @return Constant reference to member test_data_path
     */
    eProsima_user_DllExport const std::string& test_data_path() const;

    /*!
     * @brief This function returns a reference to member test_data_path
     * @return Reference to member test_data_path
     */
    eProsima_user_DllExport std::string& test_data_path();


    /*!
     * @brief This function sets a value in member test_data_type
     * @param _test_data_type New value for member test_data_type
     */
    eProsima_user_DllExport void test_data_type(
            uint32_t _test_data_type);

    /*!
     * @brief This function returns the value of member test_data_type
     * @return Value of member test_data_type
     */
    eProsima_user_DllExport uint32_t test_data_type() const;

    /*!
     * @brief This function returns a reference to member test_data_type
     * @return Reference to member test_data_type
     */
    eProsima_user_DllExport uint32_t& test_data_type();

private:

    std::vector<float> m_expected_outputs;
    std::vector<float> m_preprocessed_imgs;
    uint32_t m_img_channels{0};
    uint32_t m_img_height{0};
    uint32_t m_img_width{0};
    std::string m_test_data_path;
    uint32_t m_test_data_type{0};

};


/*!
 * @brief This class represents the structure CTimeMatchSrcData defined by the user in the IDL file.
 * @ingroup CTimeMatchSrcData
 */
class CTimeMatchSrcData : public CDataBase
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CTimeMatchSrcData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CTimeMatchSrcData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CTimeMatchSrcData that will be copied.
     */
    eProsima_user_DllExport CTimeMatchSrcData(
            const CTimeMatchSrcData& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CTimeMatchSrcData that will be copied.
     */
    eProsima_user_DllExport CTimeMatchSrcData(
            CTimeMatchSrcData&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CTimeMatchSrcData that will be copied.
     */
    eProsima_user_DllExport CTimeMatchSrcData& operator =(
            const CTimeMatchSrcData& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CTimeMatchSrcData that will be copied.
     */
    eProsima_user_DllExport CTimeMatchSrcData& operator =(
            CTimeMatchSrcData&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x CTimeMatchSrcData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CTimeMatchSrcData& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CTimeMatchSrcData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CTimeMatchSrcData& x) const;

    /*!
     * @brief This function copies the value in member vecVideoSrcData
     * @param _vecVideoSrcData New value to be copied in member vecVideoSrcData
     */
    eProsima_user_DllExport void vecVideoSrcData(
            const std::vector<CVideoSrcData>& _vecVideoSrcData);

    /*!
     * @brief This function moves the value in member vecVideoSrcData
     * @param _vecVideoSrcData New value to be moved in member vecVideoSrcData
     */
    eProsima_user_DllExport void vecVideoSrcData(
            std::vector<CVideoSrcData>&& _vecVideoSrcData);

    /*!
     * @brief This function returns a constant reference to member vecVideoSrcData
     * @return Constant reference to member vecVideoSrcData
     */
    eProsima_user_DllExport const std::vector<CVideoSrcData>& vecVideoSrcData() const;

    /*!
     * @brief This function returns a reference to member vecVideoSrcData
     * @return Reference to member vecVideoSrcData
     */
    eProsima_user_DllExport std::vector<CVideoSrcData>& vecVideoSrcData();


    /*!
     * @brief This function copies the value in member ego_pose_info
     * @param _ego_pose_info New value to be copied in member ego_pose_info
     */
    eProsima_user_DllExport void ego_pose_info(
            const CEgoPoseInfo& _ego_pose_info);

    /*!
     * @brief This function moves the value in member ego_pose_info
     * @param _ego_pose_info New value to be moved in member ego_pose_info
     */
    eProsima_user_DllExport void ego_pose_info(
            CEgoPoseInfo&& _ego_pose_info);

    /*!
     * @brief This function returns a constant reference to member ego_pose_info
     * @return Constant reference to member ego_pose_info
     */
    eProsima_user_DllExport const CEgoPoseInfo& ego_pose_info() const;

    /*!
     * @brief This function returns a reference to member ego_pose_info
     * @return Reference to member ego_pose_info
     */
    eProsima_user_DllExport CEgoPoseInfo& ego_pose_info();


    /*!
     * @brief This function copies the value in member lidar2ego_info
     * @param _lidar2ego_info New value to be copied in member lidar2ego_info
     */
    eProsima_user_DllExport void lidar2ego_info(
            const CLidar2EgoInfo& _lidar2ego_info);

    /*!
     * @brief This function moves the value in member lidar2ego_info
     * @param _lidar2ego_info New value to be moved in member lidar2ego_info
     */
    eProsima_user_DllExport void lidar2ego_info(
            CLidar2EgoInfo&& _lidar2ego_info);

    /*!
     * @brief This function returns a constant reference to member lidar2ego_info
     * @return Constant reference to member lidar2ego_info
     */
    eProsima_user_DllExport const CLidar2EgoInfo& lidar2ego_info() const;

    /*!
     * @brief This function returns a reference to member lidar2ego_info
     * @return Reference to member lidar2ego_info
     */
    eProsima_user_DllExport CLidar2EgoInfo& lidar2ego_info();


    /*!
     * @brief This function copies the value in member transform_info
     * @param _transform_info New value to be copied in member transform_info
     */
    eProsima_user_DllExport void transform_info(
            const CTransformInfo& _transform_info);

    /*!
     * @brief This function moves the value in member transform_info
     * @param _transform_info New value to be moved in member transform_info
     */
    eProsima_user_DllExport void transform_info(
            CTransformInfo&& _transform_info);

    /*!
     * @brief This function returns a constant reference to member transform_info
     * @return Constant reference to member transform_info
     */
    eProsima_user_DllExport const CTransformInfo& transform_info() const;

    /*!
     * @brief This function returns a reference to member transform_info
     * @return Reference to member transform_info
     */
    eProsima_user_DllExport CTransformInfo& transform_info();


    /*!
     * @brief This function copies the value in member lidar_data
     * @param _lidar_data New value to be copied in member lidar_data
     */
    eProsima_user_DllExport void lidar_data(
            const CLidarData& _lidar_data);

    /*!
     * @brief This function moves the value in member lidar_data
     * @param _lidar_data New value to be moved in member lidar_data
     */
    eProsima_user_DllExport void lidar_data(
            CLidarData&& _lidar_data);

    /*!
     * @brief This function returns a constant reference to member lidar_data
     * @return Constant reference to member lidar_data
     */
    eProsima_user_DllExport const CLidarData& lidar_data() const;

    /*!
     * @brief This function returns a reference to member lidar_data
     * @return Reference to member lidar_data
     */
    eProsima_user_DllExport CLidarData& lidar_data();


    /*!
     * @brief This function copies the value in member calibration_data
     * @param _calibration_data New value to be copied in member calibration_data
     */
    eProsima_user_DllExport void calibration_data(
            const CCalibrationData& _calibration_data);

    /*!
     * @brief This function moves the value in member calibration_data
     * @param _calibration_data New value to be moved in member calibration_data
     */
    eProsima_user_DllExport void calibration_data(
            CCalibrationData&& _calibration_data);

    /*!
     * @brief This function returns a constant reference to member calibration_data
     * @return Constant reference to member calibration_data
     */
    eProsima_user_DllExport const CCalibrationData& calibration_data() const;

    /*!
     * @brief This function returns a reference to member calibration_data
     * @return Reference to member calibration_data
     */
    eProsima_user_DllExport CCalibrationData& calibration_data();


    /*!
     * @brief This function copies the value in member test_data
     * @param _test_data New value to be copied in member test_data
     */
    eProsima_user_DllExport void test_data(
            const CTestSrcData& _test_data);

    /*!
     * @brief This function moves the value in member test_data
     * @param _test_data New value to be moved in member test_data
     */
    eProsima_user_DllExport void test_data(
            CTestSrcData&& _test_data);

    /*!
     * @brief This function returns a constant reference to member test_data
     * @return Constant reference to member test_data
     */
    eProsima_user_DllExport const CTestSrcData& test_data() const;

    /*!
     * @brief This function returns a reference to member test_data
     * @return Reference to member test_data
     */
    eProsima_user_DllExport CTestSrcData& test_data();

private:

    std::vector<CVideoSrcData> m_vecVideoSrcData;
    CEgoPoseInfo m_ego_pose_info;
    CLidar2EgoInfo m_lidar2ego_info;
    CTransformInfo m_transform_info;
    CLidarData m_lidar_data;
    CCalibrationData m_calibration_data;
    CTestSrcData m_test_data;

};

#endif // _FAST_DDS_GENERATED_CTIMEMATCHSRCDATA_H_



